//! `shaders/neural_mlp.wgsl` is what this test generates: the neural texture decoder's network,
//! unrolled (docs/spec/neural-textures.md 3.3). `POCKET_BLESS=1 cargo test -p pocket-render --test
//! neural_mlp` rewrites it.
//!
//! The decoder's loops ran to constants, but naga bounds every loop with a hidden counter (its
//! `force_loop_bounding` runtime check) and the drivers then kept them as loops, the activations in
//! local memory: a 1920x1080 decode took 10.7 ms in f16 on the RTX 5060 against 2.2 ms unrolled
//! (docs/bench/neural-textures.md). The generated function has no loop: a statement per 4x4 weight
//! block up to the largest profile the format allows (24 input blocks: 64 fine-grid inputs, 16
//! coarse, 12 encoding, 2 level of detail; 16 hidden blocks; 4 output blocks), each behind a
//! constant condition on the profile (`NT_*`) that drivers fold, with clamped constant indices that
//! are valid for every profile.

const IN4: u32 = 24;
const HID4: u32 = 16;
const OUT4: u32 = 4;

// "Generated", not rustfmt's marker: `cargo xtask check`'s gen step refuses that marker on a file
// no xtask generator writes (`gen.orphan`, checks.md 5.4), and this test is the generator.
const HEADER: &str = "// Generated by crates/pocket-render/tests/neural_mlp.rs (POCKET_BLESS=1 rewrites it): the\n\
// neural texture decoder's network, unrolled for every profile up to the largest; see that test\n\
// for why. Uses neural_texture.wgsl's layout constants, `nt_inputs`, `nt_mat` and `nt_bias`.\n";

struct Layer {
    name: &'static str,
    /// The previous layer's blocks: `x` (an array) or a variable prefix.
    prev: &'static str,
    prev_is_array: bool,
    outputs: u32,
    inputs: u32,
    out_blocks: &'static str,
    in_blocks: &'static str,
    weights: &'static str,
    biases: &'static str,
    relu: bool,
}

fn layer(o: &mut Vec<String>, l: &Layer) {
    for j in 0..l.outputs {
        let name = format!("{}{j}", l.name);
        o.push(format!("    var {name} = vec4<nt_t>(0.0);"));
        o.push(format!("    if {} > {j}u {{", l.out_blocks));
        o.push(format!(
            "        {name} = nt_bias(w + {} + {j}u);",
            l.biases
        ));
        for k in 0..l.inputs {
            let src = if l.prev_is_array {
                format!("{}[min({k}u, {} - 1u)]", l.prev, l.in_blocks)
            } else {
                format!("{}{k}", l.prev)
            };
            o.push(format!(
                "        if {} > {k}u {{ {name} += nt_mat(w + {} + {}u + 2u * {j}u * {}) * {src}; }}",
                l.in_blocks,
                l.weights,
                2 * k,
                l.in_blocks
            ));
        }
        if l.relu {
            o.push(format!("        {name} = max({name}, vec4<nt_t>(0.0));"));
        }
        o.push("    }".into());
    }
}

fn generate() -> String {
    let mut o: Vec<String> = vec![
        "".into(),
        "// Every channel of mip `mip` at `uv`, unclamped, in the texture's channel order (4 a vector).".into(),
        "// `weights` is the data word where the texture's weights start, read by the caller from".into(),
        "// descriptor word 2 or 3 (both hold it): two decodes reading it from different words keep a".into(),
        "// compiler from sharing, and so holding, every weight load between them (forward_neural.wgsl).".into(),
        "fn nt_decode(base: u32, weights: u32, mip: u32, uv: vec2f) -> array<vec4<nt_t>, NT_OUT4> {".into(),
        "    let x = nt_inputs(base, mip, uv);".into(),
        "    let w = weights;".into(),
    ];
    for l in [
        Layer {
            name: "a",
            prev: "x",
            prev_is_array: true,
            outputs: HID4,
            inputs: IN4,
            out_blocks: "NT_H1_4",
            in_blocks: "NT_IN4",
            weights: "NT_L1W",
            biases: "NT_L1B",
            relu: true,
        },
        Layer {
            name: "b",
            prev: "a",
            prev_is_array: false,
            outputs: HID4,
            inputs: HID4,
            out_blocks: "NT_H2_4",
            in_blocks: "NT_H1_4",
            weights: "NT_L2W",
            biases: "NT_L2B",
            relu: true,
        },
        Layer {
            name: "c",
            prev: "b",
            prev_is_array: false,
            outputs: OUT4,
            inputs: HID4,
            out_blocks: "NT_OUT4",
            in_blocks: "NT_H2_4",
            weights: "NT_L3W",
            biases: "NT_L3B",
            relu: false,
        },
    ] {
        layer(&mut o, &l);
    }
    o.push("    var y: array<vec4<nt_t>, NT_OUT4>;".into());
    for j in 0..OUT4 {
        o.push(format!(
            "    if NT_OUT4 > {j}u {{ y[min({j}u, NT_OUT4 - 1u)] = c{j}; }}"
        ));
    }
    o.push("    return y;".into());
    o.push("}".into());
    format!("{HEADER}{}\n", o.join("\n"))
}

#[test]
fn neural_mlp_wgsl_is_current() {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("shaders/neural_mlp.wgsl");
    let text = generate();
    if std::env::var_os("POCKET_BLESS").is_some() {
        std::fs::write(&path, &text).unwrap();
        return;
    }
    let committed = std::fs::read_to_string(&path)
        .unwrap_or_default()
        .replace("\r\n", "\n");
    assert!(
        committed == text,
        "shaders/neural_mlp.wgsl is stale: run with POCKET_BLESS=1"
    );
}
