//! The prelude's committed JavaScript is what `src/prelude/pocket.ts` compiles to, through the
//! same pipeline and lint as project modules (script-host.md 8.3). The web build has no
//! transpiler, so it runs the committed file; `POCKET_BLESS=1 cargo test -p pocket-script
//! --features transpile --test prelude` rewrites it after the TypeScript changes.
#![cfg(feature = "transpile")]

// "Generated", not rustfmt's marker: `cargo xtask check`'s gen step refuses that marker on a file
// no xtask generator writes (`gen.orphan`, checks.md 5.4), and this test is the generator.
const HEADER: &str =
    "// Generated by tests/prelude.rs from src/prelude/pocket.ts (POCKET_BLESS=1 rewrites it).\n";

#[test]
fn prelude_js_is_current() {
    let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("src/prelude");
    let ts = std::fs::read_to_string(dir.join("pocket.ts")).unwrap();
    let t = pocket_script::compile::compile_prelude(&ts).unwrap_or_else(|e| panic!("{e:#?}"));
    let js = format!("{HEADER}{}", t.js);
    // The header is one more line: every mapping moves down by one.
    let mut map: serde_json::Value = serde_json::from_str(&t.map).unwrap();
    let mappings = format!(";{}", map["mappings"].as_str().unwrap());
    map["mappings"] = serde_json::Value::String(mappings);
    let map = serde_json::to_string(&map).unwrap();
    if std::env::var_os("POCKET_BLESS").is_some() {
        std::fs::write(dir.join("pocket.js"), &js).unwrap();
        std::fs::write(dir.join("pocket.js.map"), &map).unwrap();
        return;
    }
    let committed = std::fs::read_to_string(dir.join("pocket.js"))
        .unwrap()
        .replace("\r\n", "\n");
    assert!(
        committed == js,
        "src/prelude/pocket.js is stale: run with POCKET_BLESS=1"
    );
    let committed_map = std::fs::read_to_string(dir.join("pocket.js.map")).unwrap();
    assert!(
        committed_map == map,
        "src/prelude/pocket.js.map is stale: run with POCKET_BLESS=1"
    );
}
