//! The prelude's committed JavaScript is what `src/prelude/pocket.ts` compiles to, through the
//! same pipeline and lint as project modules (script-host.md 8.3), and its committed declarations
//! (`pocket.d.ts`, the SDK scripts type-check against, script-host.md 7.4) are what
//! `oxc_isolated_declarations` emits from the same source, so docs and types cannot drift. The web
//! build has no transpiler, so it runs the committed file; `POCKET_BLESS=1 cargo test -p
//! pocket-script --features transpile --test prelude` rewrites both after the TypeScript changes.
#![cfg(feature = "transpile")]

use oxc_allocator::Allocator;
use oxc_codegen::{Codegen, CodegenOptions, CommentOptions};
use oxc_isolated_declarations::{IsolatedDeclarations, IsolatedDeclarationsOptions};
use oxc_parser::Parser;
use oxc_span::SourceType;

// "Generated", not rustfmt's marker: `cargo xtask check`'s gen step refuses that marker on a file
// no xtask generator writes (`gen.orphan`, checks.md 5.4), and this test is the generator.
const HEADER: &str =
    "// Generated by tests/prelude.rs from src/prelude/pocket.ts (POCKET_BLESS=1 rewrites it).\n";

fn bless() -> bool {
    std::env::var_os("POCKET_BLESS").is_some()
}

fn prelude_dir() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("src/prelude")
}

#[test]
fn prelude_js_is_current() {
    let dir = prelude_dir();
    let ts = std::fs::read_to_string(dir.join("pocket.ts")).unwrap();
    let t = pocket_script::compile::compile_prelude(&ts).unwrap_or_else(|e| panic!("{e:#?}"));
    let js = format!("{HEADER}{}", t.js);
    // The header is one more line: every mapping moves down by one.
    let mut map: serde_json::Value = serde_json::from_str(&t.map).unwrap();
    let mappings = format!(";{}", map["mappings"].as_str().unwrap());
    map["mappings"] = serde_json::Value::String(mappings);
    let map = serde_json::to_string(&map).unwrap();
    if bless() {
        std::fs::write(dir.join("pocket.js"), &js).unwrap();
        std::fs::write(dir.join("pocket.js.map"), &map).unwrap();
        return;
    }
    let committed = std::fs::read_to_string(dir.join("pocket.js"))
        .unwrap()
        .replace("\r\n", "\n");
    assert!(
        committed == js,
        "src/prelude/pocket.js is stale: run with POCKET_BLESS=1"
    );
    let committed_map = std::fs::read_to_string(dir.join("pocket.js.map")).unwrap();
    assert!(
        committed_map == map,
        "src/prelude/pocket.js.map is stale: run with POCKET_BLESS=1"
    );
}

/// The declarations of the prelude: its exports with their JSDoc, `@internal` ones left out.
fn declarations(ts: &str) -> String {
    let allocator = Allocator::default();
    let parsed = Parser::new(&allocator, ts, SourceType::ts()).parse();
    assert!(
        parsed.diagnostics.is_empty(),
        "pocket.ts does not parse: {:?}",
        parsed.diagnostics
    );
    let ret = IsolatedDeclarations::new(
        &allocator,
        IsolatedDeclarationsOptions {
            strip_internal: true,
        },
    )
    .build(&parsed.program);
    assert!(
        ret.diagnostics.is_empty(),
        "pocket.ts has exports isolated declarations cannot type: {:?}",
        ret.diagnostics
            .iter()
            .map(|d| d.to_string())
            .collect::<Vec<_>>()
    );
    Codegen::new()
        .with_options(CodegenOptions {
            comments: CommentOptions {
                jsdoc: true,
                ..CommentOptions::disabled()
            },
            ..CodegenOptions::default()
        })
        .build(&ret.program)
        .code
}

#[test]
fn prelude_dts_is_current() {
    let dir = prelude_dir();
    let ts = std::fs::read_to_string(dir.join("pocket.ts")).unwrap();
    let dts = format!("{HEADER}{}", declarations(&ts));
    assert!(
        !dts.contains("pocket:host"),
        "the SDK's declarations must not name pocket:host"
    );
    if bless() {
        std::fs::write(dir.join("pocket.d.ts"), &dts).unwrap();
        return;
    }
    let committed = std::fs::read_to_string(dir.join("pocket.d.ts"))
        .unwrap_or_default()
        .replace("\r\n", "\n");
    assert!(
        committed == dts,
        "src/prelude/pocket.d.ts is stale: run with POCKET_BLESS=1"
    );
    assert_eq!(pocket_script::types::PRELUDE_DTS, committed);
}
