#!/usr/bin/env python3
"""The playground's Enemy component (samples/playground/components.toml) through the commands an
agent uses: schema, query, set by value name, a refused field, a scene fragment, recorder.track,
save and load. Writes transcript.json beside this file. Needs a debug build and
`./.pocket/pocket ts samples/playground`; run outside the sandbox (it serves on loopback)."""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "..", "..", "tools", "scripts", "dev"))
from runtime import Runtime  # noqa: E402

calls = []


def call(r, method, params=None, expect_error=False):
    try:
        result = r.rpc(method, params or {})
        calls.append({"method": method, "params": params or {}, "result": result})
        return result
    except RuntimeError as e:
        if not expect_error:
            raise
        calls.append({"method": method, "params": params or {}, "error": str(e)})
        return None


with Runtime("playground", port=4791, size="320x180", extra=("--history", "600")) as r:
    call(r, "world.schema", {"component": "Enemy"})
    call(r, "step", {"ticks": 240})
    rows = call(r, "world.query", {"with": ["Enemy"], "fields": ["Enemy"]})
    first = rows["entities"][0]["id"]
    call(r, "world.set", {"entity": first, "component": "Enemy", "value": {"kind": "brute", "damage": 25}})
    call(r, "world.set", {"entity": first, "component": "Enemy", "value": {"damge": 5}}, expect_error=True)
    call(r, "world.instantiate", {"scene": {"format": "pocket-scene", "version": 1, "entities": [
        {"name": "Ogre", "components": {"Transform": {"position": {"x": 8, "y": 0.5, "z": 8}}, "Enemy": {"kind": "brute", "damage": 30}}}]}})
    call(r, "world.get", {"entity": "Ogre", "component": "Enemy"})
    call(r, "step", {"ticks": 60})
    call(r, "recorder.track", {"entity": first, "component": "Enemy", "field": "damage", "from": 230, "to": 299})
    saved = call(r, "world.save", {})
    call(r, "world.load", {"scene": saved})
    call(r, "world.query", {"with": ["Enemy"], "fields": ["Enemy"]})
    call(r, "world.tree", {"components": ["Enemy"], "values": True, "depth": 2})

with open(os.path.join(HERE, "transcript.json"), "w", encoding="utf-8", newline="\n") as f:
    json.dump({"note": "samples/playground with its Enemy component; generated by transcript.py", "calls": calls}, f, indent=1)
    f.write("\n")
print(f"{len(calls)} calls")
