#!/usr/bin/env python3
"""Generate engine/ui/src/bidi_classes.gen.inc, the bidirectional character types that
engine/ui/src/bidi.cpp resolves (UAX #9), from the Unicode character database Python carries.

Each entry is the first code point of a stretch of one type; the stretch ends where the next
begins. The explicit embedding, override and isolate controls come out as BN because bidi.cpp does
not read them, and a segment separator (tab) as WS. Code points not yet assigned take the type
DerivedBidiClass.txt gives their block: R or AL in the right-to-left blocks, ET for currency
symbols, BN for noncharacters and default-ignorables, L elsewhere.

Usage: python3 tools/scripts/gen_bidi_classes.py   (rerun when Python's Unicode version moves)
"""
import os
import unicodedata

KEEP = {"L", "R", "AL", "EN", "ES", "ET", "AN", "CS", "NSM", "BN", "B", "WS", "ON"}
FOLD = {"S": "WS", "LRE": "BN", "LRO": "BN", "RLE": "BN", "RLO": "BN", "PDF": "BN",
        "LRI": "BN", "RLI": "BN", "FSI": "BN", "PDI": "BN"}

# Types of unassigned code points by block (DerivedBidiClass.txt, @missing lines).
UNASSIGNED = [
    (0x0590, 0x05FF, "R"), (0x0600, 0x07BF, "AL"), (0x07C0, 0x085F, "R"), (0x0860, 0x08FF, "AL"),
    (0x20A0, 0x20CF, "ET"), (0xFB1D, 0xFB4F, "R"), (0xFB50, 0xFDCF, "AL"), (0xFDF0, 0xFDFF, "AL"),
    (0xFE70, 0xFEFF, "AL"), (0x10800, 0x10CFF, "R"), (0x10D00, 0x10D3F, "AL"),
    (0x10D40, 0x10EBF, "R"), (0x10EC0, 0x10EFF, "AL"), (0x10F00, 0x10F2F, "R"),
    (0x10F30, 0x10F6F, "AL"), (0x10F70, 0x10FFF, "R"), (0x1E800, 0x1EC6F, "R"),
    (0x1EC70, 0x1ECBF, "AL"), (0x1ECC0, 0x1ECFF, "R"), (0x1ED00, 0x1ED4F, "AL"),
    (0x1ED50, 0x1EDFF, "R"), (0x1EE00, 0x1EEFF, "AL"), (0x1EF00, 0x1EFFF, "R"),
]


def unassigned(c):
    if (0xFDD0 <= c <= 0xFDEF) or (c & 0xFFFE) == 0xFFFE:
        return "BN"
    if 0x2060 <= c <= 0x206F or 0xFFF0 <= c <= 0xFFF8 or 0xE0000 <= c <= 0xE0FFF or 0x1BCA0 <= c <= 0x1BCA3:
        return "BN"
    for lo, hi, t in UNASSIGNED:
        if lo <= c <= hi:
            return t
    return "L"


def type_of(c):
    if 0xD800 <= c <= 0xDFFF:
        return "L"
    t = unicodedata.bidirectional(chr(c))
    if not t:
        return unassigned(c)
    t = FOLD.get(t, t)
    assert t in KEEP, (hex(c), t)
    return t


def main():
    root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    out = os.path.join(root, "engine", "ui", "src", "bidi_classes.gen.inc")
    starts = []
    prev = None
    for c in range(0x110000):
        t = type_of(c)
        if t != prev:
            starts.append((c, t))
            prev = t
    lines = [f"// generated by tools/scripts/gen_bidi_classes.py from Unicode {unicodedata.unidata_version}; do not edit",
             "// {first code point, type}: each stretch runs to the next entry's first code point."]
    row = []
    for c, t in starts:
        row.append(f"{{0x{c:X}, T::{t}}}")
        if len(row) == 6:
            lines.append(", ".join(row) + ",")
            row = []
    if row:
        lines.append(", ".join(row) + ",")
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"{out}: {len(starts)} stretches")


if __name__ == "__main__":
    main()
