#!/usr/bin/env python3
"""Perception benchmark: how much an agent must read to know what is going on.

For each sample the runtime is started headless and paused, stepped for a fixed number of ticks,
and asked for the same situation in different forms. Sizes are measured exactly; tokens are
estimated at 4 characters per token for text and width*height/750 for an image, which is the
usual order of magnitude for current models. The point is the ratio between forms, not the
absolute numbers.

Usage: python3 tools/scripts/perception_bench.py [--ticks 240] [--out docs/evidence/perception.md]
"""
import argparse
import datetime
import json
import os
import subprocess
import sys
import urllib.request

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
SAMPLES = ["hello", "playground", "physics", "ui", "assets", "audio"]


def rpc(url, seq, method, params=None):
    body = json.dumps({"jsonrpc": "2.0", "id": seq, "method": method, "params": params or {}}).encode()
    req = urllib.request.Request(url + "/rpc", data=body, headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=60) as r:
        resp = json.load(r)
    if "error" in resp:
        raise RuntimeError(f"{method}: {resp['error']}")
    return resp["result"]


def tokens_text(s):
    return (len(s) + 3) // 4


def measure(sample, ticks, width, height):
    exe = os.path.join(ROOT, "build", "debug", "bin", "pocket_runtime" + (".exe" if os.name == "nt" else ""))
    bundle = os.path.join(ROOT, "build", "ts", f"{sample}.js")
    proc = subprocess.Popen([exe, "--project", os.path.join(ROOT, "samples", sample), "--bundle", bundle, "--headless", "--serve", "0", "--paused", "--json", "--size", f"{width}x{height}", "--log-level", "warn"], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, encoding="utf-8", errors="replace")
    url = None
    while url is None:
        line = proc.stderr.readline()
        if not line:
            raise RuntimeError(f"{sample}: runtime exited: {proc.stdout.read()}")
        if line.startswith('{"event":"listening"'):
            url = json.loads(line)["url"]
    seq = [0]

    def call(method, params=None):
        seq[0] += 1
        return rpc(url, seq[0], method, params)

    call("step", {"ticks": ticks})
    schema = call("world.schema")
    names = [c["name"] for c in schema["components"] if c.get("serialized", True)]
    rows = {}
    full = call("world.query", {"fields": names, "limit": 100000})
    rows["world.query (every component, JSON)"] = json.dumps(full, separators=(",", ":"))
    rows["world.tree (text)"] = call("world.tree", {})["text"] if isinstance(call("world.tree", {}), dict) else call("world.tree", {})
    rows["world.summary (JSON)"] = json.dumps(call("world.summary"), separators=(",", ":"))
    events = call("events.since", {"seq": 0, "limit": 100000})
    rows["events.since 0 (JSON)"] = json.dumps(events, separators=(",", ":"))
    rows["transcript (text)"] = call("transcript", {"max_lines": 40})["text"]
    ui = call("ui.snapshot", {"max_nodes": 500})
    if ui.get("nodes", 1) > 1:
        rows["ui.snapshot (text)"] = ui["text"]
    cap_path = os.path.join(ROOT, "build", "test-out", f"perception-{sample}.png")
    call("capture", {"path": cap_path})
    png_bytes = os.path.getsize(cap_path)
    st = call("state")
    summary = call("world.summary")
    call("quit")
    proc.wait(timeout=30)
    return {
        "sample": sample,
        "ticks": st["tick"],
        "entities": summary["entities"],
        "events": summary["events"],
        "rows": {k: {"chars": len(v), "tokens": tokens_text(v)} for k, v in rows.items()},
        "image": {"bytes": png_bytes, "pixels": width * height, "tokens": (width * height) // 750},
        "texts": rows,
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ticks", type=int, default=240)
    ap.add_argument("--size", default="960x540")
    ap.add_argument("--out", default=os.path.join(ROOT, "docs", "evidence", "perception.md"))
    args = ap.parse_args()
    w, h = (int(x) for x in args.size.split("x"))
    results = [measure(s, args.ticks, w, h) for s in SAMPLES]
    lines = []
    lines.append(f"# Perception benchmark ({datetime.date.today().isoformat()})\n")
    lines.append(f"Each sample ran headless for {args.ticks} ticks at 60 Hz in a {w}x{h} frame, then was asked for the same situation in every form the runtime offers. Sizes are exact; tokens are estimated at 4 characters per token for text and width x height / 750 for one image. Generated by `python3 tools/scripts/perception_bench.py`; the texts themselves are in `tests/evidence/perception/`.\n")
    for r in results:
        lines.append(f"## {r['sample']}: {r['entities']} entities, {r['events']} events after {r['ticks']} ticks\n")
        lines.append("| Form | Characters | Tokens (est.) |")
        lines.append("|---|---:|---:|")
        for k, v in r["rows"].items():
            lines.append(f"| `{k}` | {v['chars']:,} | {v['tokens']:,} |")
        lines.append(f"| one {w}x{h} capture (PNG {r['image']['bytes']:,} B) | - | {r['image']['tokens']:,} |")
        q = r["rows"]["world.query (every component, JSON)"]["tokens"]
        t = r["rows"]["world.tree (text)"]["tokens"]
        tr = r["rows"]["transcript (text)"]["tokens"]
        img = r["image"]["tokens"]
        lines.append("")
        lines.append(f"Tree is {q / max(t, 1):.1f}x smaller than the full JSON; the transcript summarizes {r['ticks']} ticks in {tr:,} tokens; one screenshot costs {img / max(t, 1):.1f}x the tree and shows no numbers.\n")
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    ev_dir = os.path.join(ROOT, "tests", "evidence", "perception")
    os.makedirs(ev_dir, exist_ok=True)
    for r in results:
        for k, v in r["texts"].items():
            fname = k.split(" ")[0].replace(".", "-") + ".txt"
            with open(os.path.join(ev_dir, f"{r['sample']}-{fname}"), "w", encoding="utf-8", newline="\n") as f:
                f.write(v if v.endswith("\n") else v + "\n")
    print(open(args.out, encoding="utf-8").read())


if __name__ == "__main__":
    main()
