//! The SDK's declarations for a project (script-host.md 7.4; docs/sdk.md): `pocket.d.ts`, the
//! prelude's API as `tests/prelude.rs` emits it from `prelude/pocket.ts`, and `components.d.ts`,
//! which fills its `Components` and `ComponentColumns` by declaration merging with every component
//! scripts can use, engine and project alike, from their `ComponentSchema`s. One emitter for both
//! origins, so a component's docs, field types and columns read the same wherever it comes from.
//! Text only: the runtime decides where the files go (`scripts.types`), and the type check that
//! reads them runs outside the game (`tsc`, in the server).

use std::fmt::Write as _;
use std::sync::Arc;

use bevy_ecs::prelude::World;
use pocket_sim::ComponentRegistry;
use pocket_sim::registry::{ComponentOrigin, ComponentSchema, FieldSchema, FieldType, FieldValue};

use crate::access::ScriptAccess;

/// The prelude's declarations, generated from `prelude/pocket.ts` by `tests/prelude.rs`.
pub const PRELUDE_DTS: &str = include_str!("prelude/pocket.d.ts");

/// Where a project's declarations are written, relative to its root.
pub const TYPES_DIR: &str = ".pocket/types";

/// The `tsconfig.json` written into a project that has none: the options the runtime implies
/// (script-host.md 7.4), `pocket` mapped to the generated declarations.
pub const TSCONFIG: &str = r#"{
  "//": "Written by the engine (scripts.types) for tsc and editors; pocket maps to the generated .pocket/types.",
  "compilerOptions": {
    "strict": true,
    "noEmit": true,
    "isolatedModules": true,
    "allowImportingTsExtensions": true,
    "target": "es2023",
    "lib": ["es2023"],
    "module": "esnext",
    "moduleResolution": "bundler",
    "types": [],
    "paths": { "pocket": ["./.pocket/types/pocket.d.ts"] }
  },
  "include": ["scripts"]
}
"#;

const GENERATED: &str =
    "// Generated by the engine (scripts.types) from the component registry; do not edit.\n";

/// The schema of every component scripts can use in `world` (a registry entry with a script schema
/// and an accessor, as the natives resolve names), and the names of the registered ones they
/// cannot, both ascending by name.
pub fn usable_components(world: &World) -> (Vec<Arc<ComponentSchema>>, Vec<String>) {
    let Some(reg) = world.get_resource::<ComponentRegistry>() else {
        return (Vec::new(), Vec::new());
    };
    let access = world.get_resource::<ScriptAccess>();
    let mut usable = Vec::new();
    let mut other = Vec::new();
    for e in reg.entries() {
        let schema = access.and_then(|a| {
            a.get(e.id)?;
            a.schema(e.id).cloned().or_else(|| e.script.clone())
        });
        match schema {
            Some(s) => usable.push(s),
            None => other.push(e.name.to_string()),
        }
    }
    (usable, other)
}

/// `pocket.d.ts` as a project gets it: the prelude's declarations, referencing the project's
/// `components.d.ts` so that every program resolving `pocket` sees the components.
pub fn pocket_dts() -> String {
    format!("/// <reference path=\"./components.d.ts\" />\n{PRELUDE_DTS}")
}

/// A doc comment's text, safe inside `/** */`.
fn doc_text(s: &str) -> String {
    s.trim().replace("*/", "*\\/")
}

fn number(x: f64) -> String {
    if x == 0.0 && x.is_sign_negative() {
        "-0".into()
    } else {
        format!("{x}")
    }
}

fn vector(v: &[f64]) -> String {
    let parts: Vec<String> = ["x", "y", "z", "w"]
        .iter()
        .zip(v)
        .map(|(n, x)| format!("{n}: {}", number(*x)))
        .collect();
    format!("{{{}}}", parts.join(", "))
}

/// A string as a TypeScript literal.
fn literal(s: &str) -> String {
    serde_json::to_string(s).unwrap_or_else(|_| "\"\"".into())
}

/// The field's type as `field.*` names it.
fn type_name(ty: &FieldType) -> &'static str {
    match ty {
        FieldType::F64 => "f64",
        FieldType::I32 => "i32",
        FieldType::U32 => "u32",
        FieldType::Tick => "tick",
        FieldType::Bool => "bool",
        FieldType::Entity => "entity",
        FieldType::Str => "str",
        FieldType::Enum(_) => "enum",
        FieldType::Vec2 => "vec2",
        FieldType::Vec3 => "vec3",
        FieldType::Vec4 => "vec4",
        FieldType::Quat => "quat",
    }
}

fn default_text(f: &FieldSchema) -> String {
    match (&f.default, &f.ty) {
        (FieldValue::F64(x), _) => number(*x),
        (FieldValue::I32(x), _) => x.to_string(),
        (FieldValue::U32(x), _) => x.to_string(),
        (FieldValue::Tick(t), _) => t.0.to_string(),
        (FieldValue::Bool(b), _) => b.to_string(),
        (FieldValue::Entity(e), _) => e.map_or_else(|| "null".into(), |e| e.get().to_string()),
        (FieldValue::Str(s), _) => literal(s),
        (FieldValue::Enum(i), FieldType::Enum(v)) => usize::try_from(*i)
            .ok()
            .and_then(|i| v.get(i))
            .map_or_else(|| i.to_string(), |n| literal(n)),
        (FieldValue::Enum(i), _) => i.to_string(),
        (FieldValue::Vec2(v), _) => vector(v),
        (FieldValue::Vec3(v), _) => vector(v),
        (FieldValue::Vec4(v) | FieldValue::Quat(v), _) => vector(v),
    }
}

/// The value type `world.get` gives the field.
fn value_type(ty: &FieldType) -> String {
    match ty {
        FieldType::F64 | FieldType::I32 | FieldType::U32 | FieldType::Tick => "number".into(),
        FieldType::Bool => "boolean".into(),
        FieldType::Entity => "Entity | null".into(),
        FieldType::Str => "string".into(),
        FieldType::Enum(v) => v.iter().map(|n| literal(n)).collect::<Vec<_>>().join(" | "),
        FieldType::Vec2 => "Vec2".into(),
        FieldType::Vec3 => "Vec3".into(),
        FieldType::Vec4 => "Vec4".into(),
        FieldType::Quat => "Quat".into(),
    }
}

/// The column type a query gives the field; none for a string.
fn column_type(ty: &FieldType) -> Option<&'static str> {
    Some(match ty {
        FieldType::F64 | FieldType::I32 | FieldType::U32 | FieldType::Tick => "Float64Array",
        FieldType::Bool => "BoolColumn",
        FieldType::Entity => "EntityColumn",
        FieldType::Enum(_) => "EnumColumn",
        FieldType::Vec2 => "Vec2Columns",
        FieldType::Vec3 => "Vec3Columns",
        FieldType::Vec4 | FieldType::Quat => "Vec4Columns",
        FieldType::Str => return None,
    })
}

/// What a column holds when it is not the value itself.
fn column_note(ty: &FieldType) -> Option<String> {
    match ty {
        FieldType::Bool => Some("1 for true, 0 for false".into()),
        FieldType::Entity => Some("the entity's id, 0 for none".into()),
        FieldType::Enum(v) => {
            let list: Vec<String> = v
                .iter()
                .enumerate()
                .map(|(i, n)| format!("{i} = {}", literal(n)))
                .collect();
            Some(format!("the variant's index: {}", list.join(", ")))
        }
        FieldType::I32 | FieldType::U32 | FieldType::Tick => {
            Some("whole numbers; writing 2.5 is refused".into())
        }
        _ => None,
    }
}

fn origin_text(c: &ComponentSchema) -> &'static str {
    match c.origin {
        ComponentOrigin::Engine => "engine component",
        ComponentOrigin::Project => "the game's component",
    }
}

fn write_component(out: &mut String, c: &ComponentSchema, columns: bool) {
    let _ = writeln!(
        out,
        "        /** {} ({}, version {}) */",
        doc_text(&c.doc),
        origin_text(c),
        c.version
    );
    let _ = writeln!(out, "        {}: {{", c.name);
    for f in &c.fields {
        if columns {
            let Some(ty) = column_type(&f.ty) else {
                continue;
            };
            let note = column_note(&f.ty).map_or_else(String::new, |n| format!("; {n}"));
            let _ = writeln!(
                out,
                "            /** {} ({}{note}) */",
                doc_text(&f.doc),
                type_name(&f.ty)
            );
            let _ = writeln!(out, "            readonly {}: {ty};", f.name);
        } else {
            let _ = writeln!(
                out,
                "            /** {} ({}, default {}) */",
                doc_text(&f.doc),
                type_name(&f.ty),
                default_text(f)
            );
            let _ = writeln!(
                out,
                "            readonly {}: {};",
                f.name,
                value_type(&f.ty)
            );
        }
    }
    let _ = writeln!(out, "        }};");
}

/// `components.d.ts`: every component scripts can use (`scriptable`, engine and project), merged
/// into `pocket`'s `Components` and `ComponentColumns`; `engine_only` names the registered
/// components scripts cannot name, listed in a comment so that an agent learns why they are absent.
pub fn components_dts(scriptable: &[&ComponentSchema], engine_only: &[&str]) -> String {
    let mut sorted: Vec<&ComponentSchema> = scriptable.to_vec();
    sorted.sort_by(|a, b| {
        (a.origin == ComponentOrigin::Project, &a.name)
            .cmp(&(b.origin == ComponentOrigin::Project, &b.name))
    });
    let names = |o: ComponentOrigin| {
        sorted
            .iter()
            .filter(|c| c.origin == o)
            .map(|c| &*c.name)
            .collect::<Vec<_>>()
            .join(", ")
    };
    let mut out = String::from(GENERATED);
    let _ = writeln!(
        out,
        "// Engine components: {}.",
        names(ComponentOrigin::Engine)
    );
    let _ = writeln!(
        out,
        "// The game's components (declared in scripts/): {}.",
        names(ComponentOrigin::Project)
    );
    if !engine_only.is_empty() {
        let _ = writeln!(
            out,
            "// Not available to scripts (no script schema; edit them as scene data): {}.",
            engine_only.join(", ")
        );
    }
    out.push_str("export {};\n\ndeclare module \"pocket\" {\n");
    out.push_str("    interface Components {\n");
    for c in &sorted {
        write_component(&mut out, c, false);
    }
    out.push_str("    }\n\n    interface ComponentColumns {\n");
    for c in &sorted {
        write_component(&mut out, c, true);
    }
    out.push_str("    }\n}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn components_become_values_and_columns() {
        let c = ComponentSchema::new(
            "Crew",
            ComponentOrigin::Project,
            2,
            "The crew.",
            vec![
                (
                    "take",
                    FieldType::Entity,
                    FieldValue::Entity(None),
                    "A crate.",
                ),
                (
                    "name",
                    FieldType::Str,
                    FieldValue::Str("Ann".into()),
                    "Who.",
                ),
                (
                    "mood",
                    FieldType::Enum(Arc::from(vec!["calm".into(), "cross".into()])),
                    FieldValue::Enum(1),
                    "How */ they feel.",
                ),
                (
                    "at",
                    FieldType::Vec3,
                    FieldValue::Vec3([0.0, -0.0, 1.5]),
                    "Where.",
                ),
            ],
        )
        .unwrap();
        let d = components_dts(&[&c], &["Model"]);
        assert!(d.contains("readonly take: Entity | null;"), "{d}");
        assert!(d.contains("readonly take: EntityColumn;"), "{d}");
        assert!(d.contains("readonly name: string;"), "{d}");
        assert!(!d.contains("readonly name: Float64Array"), "{d}");
        assert!(d.contains("readonly mood: \"calm\" | \"cross\";"), "{d}");
        assert!(d.contains("default \"cross\""), "{d}");
        assert!(d.contains("0 = \"calm\", 1 = \"cross\""), "{d}");
        assert!(d.contains("How *\\/ they feel."), "{d}");
        assert!(d.contains("default {x: 0, y: -0, z: 1.5}"), "{d}");
        assert!(d.contains("readonly at: Vec3Columns;"), "{d}");
        assert!(d.contains("Not available to scripts"), "{d}");
    }
}
