//! Tests of the generators and the `shared/SYNC.toml` record.

use super::*;
use crate::report::Verdict;
use std::fs;
use std::path::PathBuf;

/// The repository, found at run time: `env!` would bake in the directory the test binary was
/// built in, and cargo reuses that binary for a copy of the workspace with the same layout.
fn repo() -> PathBuf {
    PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR").expect("cargo test sets it"))
        .parent()
        .unwrap()
        .to_path_buf()
}

#[test]
fn shared_reference_carries_only_an_optional_commit() {
    let sync: Sync = config::parse(SYNC, "commit = \"source-commit\"\n").unwrap();
    assert_eq!(sync.commit, "source-commit");
    let sync: Sync = config::parse(SYNC, "commit = \"\"\n").unwrap();
    assert!(sync.commit.is_empty());
}

#[test]
fn shared_edits_need_no_checksum_record() {
    let root = std::env::temp_dir().join(format!("xtask-sync-{}", std::process::id()));
    let _ = fs::remove_dir_all(&root);
    fs::create_dir_all(root.join("tools")).unwrap();
    fs::create_dir_all(root.join("shared/contract")).unwrap();
    fs::write(
        root.join(CLIPPY_SOURCE),
        "crates = []\ndisallowed-methods = []\ndisallowed-types = []\n",
    )
    .unwrap();
    let record = "commit = \"source-commit\"\n";
    fs::write(root.join(SYNC), record).unwrap();
    let listed = vec![SYNC.to_string(), "shared/contract/a.md".to_string()];
    fs::write(root.join("shared/contract/a.md"), "a\n").unwrap();
    assert_eq!(check(&root, &listed).verdict, Verdict::Pass);
    fs::write(root.join("shared/contract/a.md"), "edited\n").unwrap();
    assert_eq!(check(&root, &listed).verdict, Verdict::Pass);
    main(&root, &crate::cli::GenOptions { check: false }).unwrap();
    assert_eq!(fs::read_to_string(root.join(SYNC)).unwrap(), record);
    fs::write(root.join(SYNC), "invalid reference record").unwrap();
    assert_eq!(check(&root, &listed).verdict, Verdict::Fail);
    let _ = fs::remove_dir_all(&root);
}

#[test]
fn every_crate_gets_the_same_clippy_toml_and_it_parses() {
    let source: ClippySource = config::load(&repo(), CLIPPY_SOURCE).unwrap();
    let outs = clippy_outputs(&source);
    assert_eq!(outs.len(), source.crates.len());
    assert!(outs.iter().all(|o| o.text == outs[0].text));
    assert!(files::is_generated(outs[0].text.as_bytes()));
    let parsed: toml::Table = outs[0].text.parse().unwrap();
    assert_eq!(
        parsed["disallowed-methods"].as_array().unwrap().len(),
        source.methods.len()
    );
    assert_eq!(
        parsed["disallowed-types"].as_array().unwrap().len(),
        source.types.len()
    );
    // The lists of simulation.md 10 and numeric.md 5.
    for path in [
        "std::time::Instant::now",
        "f64::sin",
        "f32::powf",
        "f64::mul_add",
        "bevy_ecs::system::Query::iter",
    ] {
        assert!(source.methods.iter().any(|e| e.path == path), "{path}");
    }
    assert!(
        source
            .types
            .iter()
            .any(|e| e.path == "std::collections::HashMap")
    );
}

#[test]
fn a_stale_copy_and_an_orphan_fail_the_step() {
    let root = std::env::temp_dir().join(format!("xtask-gen-{}", std::process::id()));
    let _ = fs::remove_dir_all(&root);
    fs::create_dir_all(root.join("tools")).unwrap();
    fs::create_dir_all(root.join("crates/pocket-sim")).unwrap();
    fs::create_dir_all(root.join("shared")).unwrap();
    fs::write(
        root.join(CLIPPY_SOURCE),
        "crates = [\"crates/pocket-sim\", \"crates/absent\"]\ndisallowed-methods = [{ path = \"f64::sin\", reason = \"r\" }]\ndisallowed-types = []\n",
    )
    .unwrap();
    fs::write(
        root.join("crates/pocket-sim/clippy.toml"),
        "# @generated\nold\n",
    )
    .unwrap();
    fs::write(
        root.join("crates/pocket-sim/x.rs"),
        "// @generated by hand\n",
    )
    .unwrap();
    fs::write(
        root.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n",
    )
    .unwrap();
    fs::write(root.join(SYNC), "commit = \"\"\n").unwrap();
    let listed: Vec<String> = [
        "Cargo.lock",
        "crates/pocket-sim/clippy.toml",
        "crates/pocket-sim/x.rs",
        "shared/SYNC.toml",
    ]
    .map(String::from)
    .into();
    let step = check(&root, &listed);
    assert_eq!(step.verdict, Verdict::Fail);
    let codes: Vec<(&str, &str)> = step
        .errors
        .iter()
        .map(|p| (p.code.as_str(), p.detail["path"].as_str().unwrap()))
        .collect();
    assert_eq!(
        codes,
        [
            ("gen.stale", "crates/pocket-sim/clippy.toml"),
            ("gen.orphan", "crates/pocket-sim/x.rs")
        ]
    );
    // Writing the outputs makes the copy current; the missing crate directory is left alone.
    for o in outputs(&root).unwrap() {
        fs::write(root.join(&o.path), o.text).unwrap();
    }
    assert!(!root.join("crates/absent").exists());
    let step = check(&root, &listed);
    assert_eq!(step.errors.len(), 1, "{:?}", step.errors);
    let _ = fs::remove_dir_all(&root);
}
