//! `gen` and `cargo xtask gen`: generated files are what their generators write now
//! (docs/spec/checks.md 5.4). The build-free generator writes each tick-code crate's `clippy.toml`
//! from `tools/clippy-determinism.toml` (checks.md 5.3). `shared/SYNC.toml` carries only an optional
//! source commit; shared files have no persistent checksum baseline (charter 3.9).

use crate::config;
use crate::files;
use crate::report::{Problem, StepResult};
use serde::Deserialize;
use serde_json::json;
use std::collections::BTreeSet;
use std::path::Path;

pub const CLIPPY_SOURCE: &str = "tools/clippy-determinism.toml";
pub const SYNC: &str = "shared/SYNC.toml";

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ClippySource {
    /// The directories that get a generated `clippy.toml` (simulation.md 10, checks.md 5.3).
    pub crates: Vec<String>,
    #[serde(rename = "disallowed-methods")]
    pub methods: Vec<Entry>,
    #[serde(rename = "disallowed-types")]
    pub types: Vec<Entry>,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Entry {
    pub path: String,
    pub reason: String,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Sync {
    pub commit: String,
}

/// A generated file: its path and the bytes its generator writes now.
pub struct Output {
    pub path: String,
    pub text: String,
}

fn quoted(s: &str) -> String {
    toml::Value::String(s.to_string()).to_string()
}

/// The `clippy.toml` every listed crate carries, generated from the one source.
pub fn clippy_outputs(source: &ClippySource) -> Vec<Output> {
    let mut text = String::from(
        "# @generated by `cargo xtask gen` from tools/clippy-determinism.toml (docs/spec/checks.md 5.3):\n\
         # edit that file and run `cargo xtask gen`; `cargo xtask check` fails on a copy that differs.\n",
    );
    for (key, entries) in [
        ("disallowed-methods", &source.methods),
        ("disallowed-types", &source.types),
    ] {
        text.push_str(&format!("{key} = [\n"));
        for e in entries {
            text.push_str(&format!(
                "    {{ path = {}, reason = {} }},\n",
                quoted(&e.path),
                quoted(&e.reason)
            ));
        }
        text.push_str("]\n");
    }
    source
        .crates
        .iter()
        .map(|dir| Output {
            path: format!("{dir}/clippy.toml"),
            text: text.clone(),
        })
        .collect()
}

/// Everything the build-free generators write now.
pub fn outputs(root: &Path) -> Result<Vec<Output>, Problem> {
    let source: ClippySource = config::load(root, CLIPPY_SOURCE)?;
    Ok(clippy_outputs(&source)
        .into_iter()
        .filter(|o| root.join(&o.path).parent().is_some_and(Path::is_dir))
        .collect())
}

/// The `gen` step of the check.
pub fn check(root: &Path, listed: &[String]) -> StepResult {
    let mut step = StepResult::new("gen");
    let outs = match outputs(root) {
        Ok(o) => o,
        Err(p) => {
            step.error(p);
            return step;
        }
    };
    for o in &outs {
        let now = std::fs::read_to_string(root.join(&o.path)).unwrap_or_default();
        if now != o.text {
            step.error(Problem::new(
                "gen.stale",
                format!("{} differs from what `cargo xtask gen` writes from {CLIPPY_SOURCE}; run `cargo xtask gen`", o.path),
                json!({"path": o.path, "generator": "clippy-determinism"}),
            ));
        }
    }
    let registered: BTreeSet<&str> = outs.iter().map(|o| o.path.as_str()).collect();
    let mut generated = 0;
    for path in listed {
        let Ok(bytes) = std::fs::read(root.join(path)) else {
            continue;
        };
        if !files::is_generated(&bytes) {
            continue;
        }
        generated += 1;
        // Cargo writes its lock files itself and marks them @generated.
        if registered.contains(path.as_str()) || path.rsplit('/').next() == Some("Cargo.lock") {
            continue;
        }
        step.error(Problem::new(
            "gen.orphan",
            format!("{path} says @generated, but no registered generator writes it"),
            json!({"path": path}),
        ));
    }
    if let Err(p) = config::load::<Sync>(root, SYNC) {
        step.error(p);
    }
    step.measure("gen.outputs", outs.len() as f64, "count");
    step.summary = format!(
        "{} clippy.toml copies, {generated} @generated files; the engine's generators (pocket gen) are not built yet",
        outs.len()
    );
    step
}

/// `cargo xtask gen [--check]`: writes (or with `--check` compares) the generated files.
pub fn main(root: &Path, opts: &crate::cli::GenOptions) -> Result<Vec<Problem>, Problem> {
    let listed = || {
        files::list(root).map_err(|m| Problem::new("check.tool_missing", m, json!({"tool": "git"})))
    };
    if opts.check {
        return Ok(check(root, &listed()?).errors);
    }
    for o in outputs(root)? {
        let path = root.join(&o.path);
        if std::fs::read_to_string(&path).ok().as_deref() != Some(o.text.as_str()) {
            std::fs::write(&path, &o.text)
                .map_err(|e| config::invalid(&o.path, None, &e.to_string()))?;
            eprintln!("wrote {}", o.path);
        }
    }
    Ok(Vec::new())
}

#[cfg(test)]
#[path = "generate_tests.rs"]
mod tests;
