[package]
name = "pocket-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
description = "The native binary `pocket`"

[[bin]]
name = "pocket"
path = "src/main.rs"

[dependencies]
pocket-contract.workspace = true
pocket-sim.workspace = true
pocket-link.workspace = true
pocket-runtime = { workspace = true, features = ["thread", "transpile"] }
pocket-check = { workspace = true, features = ["native"] }
serde_json.workspace = true
pocket-assets.workspace = true
pocket-render = { workspace = true, features = ["window", "import"] }
glam.workspace = true
image.workspace = true
