// Generated by tests/prelude.rs from src/prelude/pocket.ts (POCKET_BLESS=1 rewrites it).
// The `pocket` module scripts import (docs/spec/script-host.md 5.1 and 8.3; docs/sdk.md): the
// builders that declare a game, and the system context over the natives of `pocket:host`, each of
// which validates its arguments. Built into the engine through the same pipeline as project modules
// and held to the same lint; `src/prelude/pocket.js` and `src/prelude/pocket.d.ts` are generated
// from it (tests/prelude.rs). The types are the SDK: `Components` and `ComponentColumns` are empty
// here and filled per project by the generated `.pocket/types/components.d.ts` (scripts.types), so
// component and field names are checked by `tsc` and completed by editors.
import * as host from "pocket:host";
/**
* A batch query's rows in ascending entity id, its columns typed arrays indexed by row:
* `q.cols.Boat.speed[row]`. Columns are the system's own copies; cells it changes are written back
* when `run` returns.
*/
export class Query {
	/** The number of rows. */
	len;
	/** Each row's entity, ascending. */
	ids;
	/** Per `with` component, its columns. */
	cols;
	/** @internal */
	constructor(raw) {
		this.len = raw.len;
		this.ids = raw.ids;
		this.cols = raw.cols;
		Object.freeze(this);
	}
	/** The entity of a row. */
	id(row) {
		return this.ids[row];
	}
	/** The row of an entity by binary search; -1 when absent. */
	row(e) {
		const ids = this.ids;
		let lo = 0;
		let hi = this.len - 1;
		while (lo <= hi) {
			const mid = lo + hi >> 1;
			const v = ids[mid];
			if (v === e) return mid;
			if (v < e) lo = mid + 1;
			else hi = mid - 1;
		}
		return -1;
	}
	/** Calls `fn(row, entity)` for every row; an error thrown names the row's entity. */
	each(fn) {
		const ids = this.ids;
		const n = this.len;
		for (let i = 0; i < n; i++) {
			try {
				fn(i, ids[i]);
			} catch (err) {
				throw annotate(err, ids[i]);
			}
		}
	}
}
function annotate(err, entity) {
	if (typeof err === "object" && err !== null && Object.isExtensible(err) && !("entity" in err)) {
		err.entity = entity;
	}
	return err;
}
/** The world as a system sees it: queries see the world as the system started, these calls the
* overlay of its own commands (script-host.md 5.4). */
const world = Object.freeze({
	exists: host.exists,
	has: host.has,
	get: host.get,
	set: host.set,
	insert: host.insert,
	remove: host.remove,
	despawn: host.despawn,
	spawn: host.spawn
});
const part = Object.freeze({ 
/** An entity as a key part of a random stream. */
entity: (e) => Object.freeze({ __pocketEntityPart: e }) });
function makeRng(h) {
	return Object.freeze({
		next: () => host.rngNext(h),
		int: (lo, hi) => host.rngInt(h, lo, hi),
		range: (lo, hi) => host.rngRange(h, lo, hi),
		chance: (p) => host.rngChance(h, p),
		pick: (items) => items[host.rngPick(h, items.length)],
		shuffle: (items) => {
			const perm = host.rngShuffle(h, items.length);
			const copy = items.slice();
			for (let i = 0; i < perm.length; i++) items[i] = copy[perm[i]];
			return items;
		},
		weighted: (weights) => host.rngWeighted(h, weights),
		normal: (mean, sd) => host.rngNormal(h, mean, sd),
		fill: (out) => {
			host.rngFill(h, out);
		}
	});
}
/** @internal The context of one system call, frozen; nothing in it outlives the call. */
export function __context(info) {
	return Object.freeze({
		tick: info.tick,
		dt: info.dt,
		time: info.time,
		system: info.system,
		world,
		rng: makeRng(host.rngSystem()),
		events: host.events(info.events),
		part,
		rngFor: (e) => makeRng(host.rngEntity(e)),
		rngNamed: (...parts) => makeRng(host.rngNamed(parts)),
		rngTimeless: (...parts) => makeRng(host.rngTimeless(parts)),
		single: (component) => host.single(component),
		query: (spec) => new Query(host.query(spec)),
		emit: (kind, data, options) => host.emit(kind, data, options),
		intent: (actor, kind, params) => host.intent(actor, kind, params)
	});
}
/** @internal The host wraps a declared query's raw columns with this. */
export function __query(raw) {
	return new Query(raw);
}
/**
* @pure A project component's declaration (script-host.md 7.3):
* `component("Tally", {version: 1, doc: "...", fields: {taken: field.u32(0, "Crates taken.")}})`.
*/
export function component(name, def) {
	return Object.freeze({
		__pocket: "component",
		name,
		def
	});
}
/**
* @pure A system of the game (script-host.md 5.1). Its queries' components and fields are checked
* against the project's components, and `run`'s second argument is typed from them:
* `queries: {boats: {with: ["Boat"], fields: ["Boat.speed"]}}` gives `boats.cols.Boat.speed`, a
* `Float64Array` indexed by row.
*/
export function system(def) {
	return Object.freeze({
		__pocket: "system",
		def
	});
}
/** @pure A system that carries out intents (script-host.md 5.5); `game()` refuses it before slice 2. */
export function executor(def) {
	return Object.freeze({
		__pocket: "executor",
		def
	});
}
/** @pure The game: the entry module's default export (script-host.md 4.2). */
export function game(def) {
	return Object.freeze({
		__pocket: "game",
		def
	});
}
/** @pure Deep-freezes a value. */
export function freeze(value) {
	return host.freeze(value);
}
const fieldOf = (type, value, doc, variants) => Object.freeze({
	__pocket: "field",
	type,
	value,
	doc,
	variants
});
/** @pure The field builders: a default, then the field's doc. */
export const field = Object.freeze({
	f64: (value, doc) => fieldOf("f64", value, doc),
	i32: (value, doc) => fieldOf("i32", value, doc),
	u32: (value, doc) => fieldOf("u32", value, doc),
	tick: (value, doc) => fieldOf("tick", value, doc),
	bool: (value, doc) => fieldOf("bool", value, doc),
	str: (value, doc) => fieldOf("str", value, doc),
	entity: (doc) => fieldOf("entity", null, doc),
	vec2: (value, doc) => fieldOf("vec2", value, doc),
	vec3: (value, doc) => fieldOf("vec3", value, doc),
	vec4: (value, doc) => fieldOf("vec4", value, doc),
	quat: (value, doc) => fieldOf("quat", value, doc),
	enum: (variants, value, doc) => fieldOf("enum", value, doc, variants)
});

import { harden as __pocket_harden } from "pocket:host";
import * as __pocket_self from "pocket";
__pocket_harden("pocket", __pocket_self, { ["Query"]: Query, ["annotate"]: annotate, ["world"]: world, ["part"]: part, ["makeRng"]: makeRng, ["__context"]: __context, ["__query"]: __query, ["component"]: component, ["system"]: system, ["executor"]: executor, ["game"]: game, ["freeze"]: freeze, ["fieldOf"]: fieldOf, ["field"]: field }, { ["Query"]: 263, ["annotate"]: 349, ["world"]: 358, ["part"]: 369, ["makeRng"]: 374, ["__context"]: 396, ["__query"]: 418, ["component"]: 549, ["system"]: 562, ["executor"]: 569, ["game"]: 574, ["freeze"]: 579, ["fieldOf"]: 621, ["field"]: 625 });
