// generated by `pocket gen`; do not edit
#pragma once

#define POCKET_COMPONENT_LIST(X) \
    X(Transform) \
    X(WorldTransform) \
    X(Velocity) \
    X(Health) \
    X(Lifetime) \
    X(Camera) \
    X(Light) \
    X(MeshRenderer) \
    X(Bounds)
