// generated by `pocket gen` from engine/*/meta/*.toml; do not edit
#pragma once

#include <pocket/core/json.hpp>
#include <pocket/core/math.hpp>
#include <pocket/core/result.hpp>

#include <cstdint>
#include <span>
#include <string>
#include <string_view>

namespace pocket::world {

struct Color4 {
    float r = 1, g = 1, b = 1, a = 1;
    constexpr bool operator==(const Color4&) const = default;
};

/// Position, rotation and scale relative to the parent entity (or the world when there is no parent).
struct Transform {
    Vec3 position{0.0f, 0.0f, 0.0f};
    Quat rotation{0.0f, 0.0f, 0.0f, 1.0f};
    Vec3 scale{1.0f, 1.0f, 1.0f};
    constexpr bool operator==(const Transform&) const = default;
};
void to_json(Json& j, const Transform& v);
void from_json(const Json& j, Transform& v);

/// World-space transform computed from the Transform hierarchy every tick. Read only.
struct WorldTransform {
    Vec3 position{0.0f, 0.0f, 0.0f};
    Quat rotation{0.0f, 0.0f, 0.0f, 1.0f};
    Vec3 scale{1.0f, 1.0f, 1.0f};
    constexpr bool operator==(const WorldTransform&) const = default;
};
void to_json(Json& j, const WorldTransform& v);
void from_json(const Json& j, WorldTransform& v);

/// Linear and angular velocity. The built-in motion system integrates Transform from it every tick.
struct Velocity {
    Vec3 linear{0.0f, 0.0f, 0.0f};
    Vec3 angular{0.0f, 0.0f, 0.0f};
    constexpr bool operator==(const Velocity&) const = default;
};
void to_json(Json& j, const Velocity& v);
void from_json(const Json& j, Velocity& v);

/// Hit points. Gameplay decides what zero means; the engine only stores and reports it.
struct Health {
    float current = 100.0f;
    float max = 100.0f;
    constexpr bool operator==(const Health&) const = default;
};
void to_json(Json& j, const Health& v);
void from_json(const Json& j, Health& v);

/// Seconds remaining before the entity is destroyed by the lifetime system.
struct Lifetime {
    float seconds = 1.0f;
    constexpr bool operator==(const Lifetime&) const = default;
};
void to_json(Json& j, const Lifetime& v);
void from_json(const Json& j, Lifetime& v);

/// Perspective camera. The renderer uses the first active camera.
struct Camera {
    float fov_degrees = 60.0f;
    float near = 0.1f;
    float far = 1000.0f;
    bool active = true;
    constexpr bool operator==(const Camera&) const = default;
};
void to_json(Json& j, const Camera& v);
void from_json(const Json& j, Camera& v);

/// A light source. kind 0 = directional (shines along -Z of the entity), 1 = point.
struct Light {
    std::int32_t kind = 0;
    Color4 color{1.0f, 1.0f, 1.0f, 1.0f};
    float intensity = 1.0f;
    float range = 10.0f;
    constexpr bool operator==(const Light&) const = default;
};
void to_json(Json& j, const Light& v);
void from_json(const Json& j, Light& v);

/// Draws a mesh: a built-in primitive or a glTF file from the project's assets, tinted by a color and optionally textured.
struct MeshRenderer {
    std::string mesh = "cube";
    Color4 color{0.8f, 0.8f, 0.8f, 1.0f};
    std::string texture = "";
    bool visible = true;
    constexpr bool operator==(const MeshRenderer&) const = default;
};
void to_json(Json& j, const MeshRenderer& v);
void from_json(const Json& j, MeshRenderer& v);

/// Axis-aligned bounding box in world space, computed by the engine from the mesh and WorldTransform. Read only.
struct Bounds {
    Vec3 min{0.0f, 0.0f, 0.0f};
    Vec3 max{0.0f, 0.0f, 0.0f};
    constexpr bool operator==(const Bounds&) const = default;
};
void to_json(Json& j, const Bounds& v);
void from_json(const Json& j, Bounds& v);

/// Physics body. Dynamic bodies fall and collide; static bodies never move; kinematic bodies move by their Velocity and push dynamic ones. Uses the entity's Transform as world space (physics entities should be roots).
struct RigidBody {
    std::int32_t kind = 0;
    float mass = 1.0f;
    float restitution = 0.2f;
    float friction = 0.5f;
    float linear_damping = 0.01f;
    float angular_damping = 0.05f;
    float gravity_scale = 1.0f;
    bool sleeping = false;
    constexpr bool operator==(const RigidBody&) const = default;
};
void to_json(Json& j, const RigidBody& v);
void from_json(const Json& j, RigidBody& v);

/// Collision shape centered on the entity (plus offset). Box half extents come from size; spheres use size.x as radius. Triggers report overlaps but do not push.
struct Collider {
    std::int32_t shape = 0;
    Vec3 size{0.5f, 0.5f, 0.5f};
    Vec3 offset{0.0f, 0.0f, 0.0f};
    bool is_trigger = false;
    constexpr bool operator==(const Collider&) const = default;
};
void to_json(Json& j, const Collider& v);
void from_json(const Json& j, Collider& v);

struct FieldInfo {
    std::string_view name;
    std::string_view type;
    std::string_view doc;
};

struct ComponentInfo {
    std::string_view name;
    std::string_view doc;
    bool serialized;
    std::span<const FieldInfo> fields;
};

/// Every component known to the engine, in metadata order.
std::span<const ComponentInfo> component_infos();

/// Hash a component value into a state hasher (all fields, in metadata order).
void hash_component(struct StateHasherRef& h, const Transform& v);
void hash_component(struct StateHasherRef& h, const WorldTransform& v);
void hash_component(struct StateHasherRef& h, const Velocity& v);
void hash_component(struct StateHasherRef& h, const Health& v);
void hash_component(struct StateHasherRef& h, const Lifetime& v);
void hash_component(struct StateHasherRef& h, const Camera& v);
void hash_component(struct StateHasherRef& h, const Light& v);
void hash_component(struct StateHasherRef& h, const MeshRenderer& v);
void hash_component(struct StateHasherRef& h, const Bounds& v);
void hash_component(struct StateHasherRef& h, const RigidBody& v);
void hash_component(struct StateHasherRef& h, const Collider& v);

}  // namespace pocket::world
