// generated by `pocket gen` from engine/*/meta/*.toml; do not edit
#pragma once

#include <pocket/core/json.hpp>
#include <pocket/core/math.hpp>
#include <pocket/core/result.hpp>

#include <cstdint>
#include <span>
#include <string>
#include <string_view>
#include <vector>

namespace pocket::world {

struct Color4 {
    float r = 1, g = 1, b = 1, a = 1;
    constexpr bool operator==(const Color4&) const = default;
};

// "#rgb", "#rgba", "#rrggbb" or "#rrggbbaa" (the # optional) as a color picker shows it; false (and `out` as it was) for anything else.
bool parse_hex_color(std::string_view text, Color4& out);

// Records: the values held by list fields of components.
/// One level of detail of a MeshRenderer (docs/design/rendering.md, Levels of detail): a simpler mesh drawn when the entity is small on screen.
struct MeshLod {
    float screen = 0.25f;
    float ratio = 0.5f;
    std::string mesh = "";
    constexpr bool operator==(const MeshLod&) const = default;
};
void to_json(Json& j, const MeshLod& v);
void from_json(const Json& j, MeshLod& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(MeshLod& v, std::string_view path, float** out);
void hash_record(struct StateHasherRef& h, const MeshLod& v);

/// One morph target weight set by script (docs/design/animation.md, Morph targets): the target by name or index, and the weight that replaces the clip's for it.
struct MorphWeight {
    std::string target = "";
    float weight = 0.0f;
    constexpr bool operator==(const MorphWeight&) const = default;
};
void to_json(Json& j, const MorphWeight& v);
void from_json(const Json& j, MorphWeight& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(MorphWeight& v, std::string_view path, float** out);
void hash_record(struct StateHasherRef& h, const MorphWeight& v);

/// The bend one joint of an IK chain may have, in degrees, measured between its bone and the bone above it, and, with `side`, the one way it bends (docs/design/animation.md, Inverse kinematics): the chain's `max_bend` is the default for the joints without an entry.
struct IKLimit {
    std::string joint = "";
    float min_bend = 0.0f;
    float max_bend = 180.0f;
    Vec3 side{0.0f, 0.0f, 0.0f};
    constexpr bool operator==(const IKLimit&) const = default;
};
void to_json(Json& j, const IKLimit& v);
void from_json(const Json& j, IKLimit& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(IKLimit& v, std::string_view path, float** out);
void hash_record(struct StateHasherRef& h, const IKLimit& v);

/// One wheel of a Vehicle (docs/design/physics.md, Vehicles): where its suspension hangs from the body, how long it is and how big the wheel, whether it steers and whether the engine drives it; the engine writes what it touches and turns.
struct Wheel {
    Vec3 offset{0.0f, 0.0f, 0.0f};
    float radius = 0.35f;
    float rest = 0.3f;
    bool steer = false;
    bool drive = false;
    std::string visual = "";
    bool contact = false;
    float compression = 0.0f;
    float spin = 0.0f;
    constexpr bool operator==(const Wheel&) const = default;
};
void to_json(Json& j, const Wheel& v);
void from_json(const Json& j, Wheel& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Wheel& v, std::string_view path, float** out);
void hash_record(struct StateHasherRef& h, const Wheel& v);

/// A moment of a clip that is announced (docs/design/animation.md, Cues): when the playing clip passes `time`, an animation.cue event names it. A footstep, the frame a swing should hurt, the moment a door's latch clicks.
struct AnimationCue {
    std::string clip = "";
    float time = 0.0f;
    std::string name = "";
    constexpr bool operator==(const AnimationCue&) const = default;
};
void to_json(Json& j, const AnimationCue& v);
void from_json(const Json& j, AnimationCue& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(AnimationCue& v, std::string_view path, float** out);
void hash_record(struct StateHasherRef& h, const AnimationCue& v);

/// One clip layered over an Animator's base clip (docs/design/animation.md): sampled at its own time, limited to the nodes of `mask`, and either blended in at `weight` or added as the clip's change since its first frame. animation.layer adds, updates and removes layers.
struct AnimationLayer {
    std::string clip = "";
    float weight = 1.0f;
    std::string mask = "";
    bool additive = false;
    bool playing = true;
    bool loop = true;
    float speed = 1.0f;
    float time = 0.0f;
    constexpr bool operator==(const AnimationLayer&) const = default;
};
void to_json(Json& j, const AnimationLayer& v);
void from_json(const Json& j, AnimationLayer& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(AnimationLayer& v, std::string_view path, float** out);
void hash_record(struct StateHasherRef& h, const AnimationLayer& v);

/// A clip mixed into an Animator's base clip at a weight, in step with it: its time is the base clip's phase of its own length.
struct AnimationBlend {
    std::string clip = "";
    float weight = 0.0f;
    constexpr bool operator==(const AnimationBlend&) const = default;
};
void to_json(Json& j, const AnimationBlend& v);
void from_json(const Json& j, AnimationBlend& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(AnimationBlend& v, std::string_view path, float** out);
void hash_record(struct StateHasherRef& h, const AnimationBlend& v);

/// One state of an AnimationGraph (docs/design/animation.md, State machines): a clip, or clips blended along a parameter.
struct AnimationState {
    std::string name = "";
    std::string clip = "";
    std::string blend = "";
    std::string clips = "";
    float speed = 1.0f;
    bool loop = true;
    constexpr bool operator==(const AnimationState&) const = default;
};
void to_json(Json& j, const AnimationState& v);
void from_json(const Json& j, AnimationState& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(AnimationState& v, std::string_view path, float** out);
void hash_record(struct StateHasherRef& h, const AnimationState& v);

/// A way out of a state in an AnimationGraph: taken, the first of those that hold in list order, when its condition holds and enough of the state has played.
struct AnimationTransition {
    std::string from = "*";
    std::string to = "";
    std::string when = "";
    float after = 0.0f;
    float fade = 0.2f;
    constexpr bool operator==(const AnimationTransition&) const = default;
};
void to_json(Json& j, const AnimationTransition& v);
void from_json(const Json& j, AnimationTransition& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(AnimationTransition& v, std::string_view path, float** out);
void hash_record(struct StateHasherRef& h, const AnimationTransition& v);

/// A value an AnimationGraph's conditions and blend spaces read, set by scripts (animation.param, animation.trigger).
struct AnimationParam {
    std::string name = "";
    float value = 0.0f;
    bool trigger = false;
    constexpr bool operator==(const AnimationParam&) const = default;
};
void to_json(Json& j, const AnimationParam& v);
void from_json(const Json& j, AnimationParam& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(AnimationParam& v, std::string_view path, float** out);
void hash_record(struct StateHasherRef& h, const AnimationParam& v);

/// One textured layer of a Terrain's ground (docs/design/terrain.md, Layers): an image tiled over the ground where the layer lies, which is where its slope and height rules put it and where it is painted.
struct TerrainLayer {
    std::string name = "";
    std::string texture = "";
    Color4 color{1.0f, 1.0f, 1.0f, 1.0f};
    float tile = 4.0f;
    Vec2 slope{0.0f, 90.0f};
    Vec2 height{0.0f, 1.0f};
    float cover = 1.0f;
    constexpr bool operator==(const TerrainLayer&) const = default;
};
void to_json(Json& j, const TerrainLayer& v);
void from_json(const Json& j, TerrainLayer& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(TerrainLayer& v, std::string_view path, float** out);
void hash_record(struct StateHasherRef& h, const TerrainLayer& v);

/// A point of a Path, in its entity's own space (docs/design/paths.md).
struct PathPoint {
    float x = 0.0f;
    float y = 0.0f;
    float z = 0.0f;
    constexpr bool operator==(const PathPoint&) const = default;
};
void to_json(Json& j, const PathPoint& v);
void from_json(const Json& j, PathPoint& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(PathPoint& v, std::string_view path, float** out);
void hash_record(struct StateHasherRef& h, const PathPoint& v);

/// A point in a 2D shape's own space (docs/design/physics2d.md).
struct Point2D {
    float x = 0.0f;
    float y = 0.0f;
    constexpr bool operator==(const Point2D&) const = default;
};
void to_json(Json& j, const Point2D& v);
void from_json(const Json& j, Point2D& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Point2D& v, std::string_view path, float** out);
void hash_record(struct StateHasherRef& h, const Point2D& v);

/// One state of a Behavior (docs/design/behavior.md): how the entity moves while in it, and what entering it plays and says.
struct BehaviorState {
    std::string name = "";
    std::int32_t move = 0;
    float speed = 0.0f;
    float radius = 5.0f;
    std::string path = "";
    std::string clip = "";
    std::string event = "";
    bool face = false;
    constexpr bool operator==(const BehaviorState&) const = default;
};
void to_json(Json& j, const BehaviorState& v);
void from_json(const Json& j, BehaviorState& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(BehaviorState& v, std::string_view path, float** out);
void hash_record(struct StateHasherRef& h, const BehaviorState& v);

/// A way from one state of a Behavior to another, taken (the first of those that hold, in list order) when its condition holds.
struct BehaviorTransition {
    std::string from = "*";
    std::string to = "";
    std::string when = "";
    std::string on = "";
    constexpr bool operator==(const BehaviorTransition&) const = default;
};
void to_json(Json& j, const BehaviorTransition& v);
void from_json(const Json& j, BehaviorTransition& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(BehaviorTransition& v, std::string_view path, float** out);
void hash_record(struct StateHasherRef& h, const BehaviorTransition& v);

/// Position, rotation and scale relative to the parent entity (or the world when there is no parent).
struct Transform {
    Vec3 position{0.0f, 0.0f, 0.0f};
    Quat rotation{0.0f, 0.0f, 0.0f, 1.0f};
    Vec3 scale{1.0f, 1.0f, 1.0f};
    constexpr bool operator==(const Transform&) const = default;
};
void to_json(Json& j, const Transform& v);
void from_json(const Json& j, Transform& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Transform& v, std::string_view path, float** out);

/// World-space transform computed from the Transform hierarchy every tick. Read only.
struct WorldTransform {
    Vec3 position{0.0f, 0.0f, 0.0f};
    Quat rotation{0.0f, 0.0f, 0.0f, 1.0f};
    Vec3 scale{1.0f, 1.0f, 1.0f};
    constexpr bool operator==(const WorldTransform&) const = default;
};
void to_json(Json& j, const WorldTransform& v);
void from_json(const Json& j, WorldTransform& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(WorldTransform& v, std::string_view path, float** out);

/// Linear and angular velocity. The built-in motion system integrates Transform from it every tick.
struct Velocity {
    Vec3 linear{0.0f, 0.0f, 0.0f};
    Vec3 angular{0.0f, 0.0f, 0.0f};
    constexpr bool operator==(const Velocity&) const = default;
};
void to_json(Json& j, const Velocity& v);
void from_json(const Json& j, Velocity& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Velocity& v, std::string_view path, float** out);

/// Hit points. Hitboxes take them (docs/design/combat.md); gameplay decides what zero means beyond the health.depleted event.
struct Health {
    float current = 100.0f;
    float max = 100.0f;
    std::int32_t team = 0;
    float invulnerable = 0.0f;
    float guard = 0.0f;
    bool dead = false;
    constexpr bool operator==(const Health&) const = default;
};
void to_json(Json& j, const Health& v);
void from_json(const Json& j, Health& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Health& v, std::string_view path, float** out);

/// Hurts what it touches (docs/design/combat.md): on a trigger collider or an Area2D, every entity with a Health that comes into it takes `damage` (a `hit` event, caused by the touch), is pushed away by `knockback`, and again every `repeat` seconds while it stays. Spikes, a sword's swing, a bullet (destroy), lava (repeat), a healing spring (negative damage).
struct Hitbox {
    float damage = 10.0f;
    float knockback = 0.0f;
    std::int32_t team = 0;
    float repeat = 0.0f;
    bool destroy = false;
    bool enabled = true;
    std::int32_t hits = 0;
    constexpr bool operator==(const Hitbox&) const = default;
};
void to_json(Json& j, const Hitbox& v);
void from_json(const Json& j, Hitbox& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Hitbox& v, std::string_view path, float** out);

/// An instance of a model file: world.instantiate {mesh} puts it on the root it makes, and when the file changes (assets.reload, assets.import, or `pocket watch` seeing it saved) a live instance is made again from it in place, its children replaced and the root kept (docs/design/assets.md, Live models).
struct Model {
    std::string path = "";
    std::string hash = "";
    bool live = true;
    constexpr bool operator==(const Model&) const = default;
};
void to_json(Json& j, const Model& v);
void from_json(const Json& j, Model& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Model& v, std::string_view path, float** out);

/// Seconds remaining before the entity is destroyed by the lifetime system.
struct Lifetime {
    float seconds = 1.0f;
    constexpr bool operator==(const Lifetime&) const = default;
};
void to_json(Json& j, const Lifetime& v);
void from_json(const Json& j, Lifetime& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Lifetime& v, std::string_view path, float** out);

/// A view of the world. With one active camera the renderer draws the window through it (the highest priority, then the first, if several have the whole window, blending to it over the incoming one's `blend`); active cameras with a viewport each draw their part of the window, in order: split screen, a minimap in a corner, a rear-view mirror (docs/design/cameras.md, Several cameras). Perspective by default; orthographic for 2D (looking down -Z with +Y up is the 2D convention).
struct Camera {
    float fov_degrees = 60.0f;
    bool orthographic = false;
    float ortho_size = 5.0f;
    float near = 0.1f;
    float far = 1000.0f;
    bool active = true;
    Vec4 viewport{0.0f, 0.0f, 1.0f, 1.0f};
    std::int32_t order = 0;
    std::string target = "";
    Vec2 target_size{256.0f, 256.0f};
    std::int32_t priority = 0;
    float blend = 0.0f;
    constexpr bool operator==(const Camera&) const = default;
};
void to_json(Json& j, const Camera& v);
void from_json(const Json& j, Camera& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Camera& v, std::string_view path, float** out);

/// Moves its entity (a camera) with a target (docs/design/cameras.md): behind it as it turns (chase), round it at a yaw and pitch a script or two input actions steer (orbit), or at a fixed offset in the world (a top-down or isometric view); always looking at the target, easing after it, brought in front of walls between them, and shaken on request. Runs after the physics and the characters each tick; the entity should be a root (its Transform is the world's).
struct CameraRig {
    std::string target = "";
    std::int32_t mode = 0;
    float distance = 6.0f;
    float height = 1.0f;
    float pitch = -20.0f;
    float yaw = 0.0f;
    Vec3 offset{0.0f, 10.0f, 8.0f};
    float follow = 0.15f;
    float turn = 0.4f;
    bool collide = true;
    std::string orbit_x = "";
    std::string orbit_y = "";
    float orbit_speed = 120.0f;
    float pitch_min = -80.0f;
    float pitch_max = 30.0f;
    float shake = 0.0f;
    float shake_decay = 1.5f;
    float heading = 0.0f;
    std::string targets = "";
    float margin = 1.5f;
    std::string rail = "";
    float look_ahead = 0.0f;
    constexpr bool operator==(const CameraRig&) const = default;
};
void to_json(Json& j, const CameraRig& v);
void from_json(const Json& j, CameraRig& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(CameraRig& v, std::string_view path, float** out);

/// A light source. kind 0 = directional (shines along -Z of the entity), 1 = point, 2 = spot (a cone along -Z of the entity). Any number of point and spot lights (docs/design/rendering.md, Many lights).
struct Light {
    std::int32_t kind = 0;
    Color4 color{1.0f, 1.0f, 1.0f, 1.0f};
    float intensity = 1.0f;
    float range = 10.0f;
    float inner_angle = 20.0f;
    float outer_angle = 30.0f;
    bool after_dark = false;
    bool shadows = false;
    constexpr bool operator==(const Light&) const = default;
};
void to_json(Json& j, const Light& v);
void from_json(const Json& j, Light& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Light& v, std::string_view path, float** out);

/// The light inside a box (docs/design/rendering.md, Reflection probes): the scene seen from the entity's position, captured into an environment of its own, in place of the sky's, both what glossy surfaces reflect and the diffuse light all surfaces get. A room's floor then reflects the room, not the sky outside, and a closed room is lit by its lamps and walls, not by the sky above its roof. Up to eight at once, the first by id where boxes overlap.
struct ReflectionProbe {
    Vec3 size{10.0f, 4.0f, 10.0f};
    float intensity = 1.0f;
    bool box_projection = true;
    bool realtime = false;
    bool enabled = true;
    constexpr bool operator==(const ReflectionProbe&) const = default;
};
void to_json(Json& j, const ReflectionProbe& v);
void from_json(const Json& j, ReflectionProbe& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(ReflectionProbe& v, std::string_view path, float** out);

/// Light probes in a grid through a box (docs/design/rendering.md, Irradiance volumes): each probe sees the scene around it, and every surface in the box takes its diffuse light from the probes nearest it, weighed by how near they are and whether they face it. Light that bounces off a red wall then reddens the floor beside the wall and not the far side of the room, and a corner away from the lamp is darker than the middle. Its diffuse light takes the place of the sky's and a reflection probe's; reflections stay theirs. Up to four at once, the first by id where boxes overlap.
struct IrradianceVolume {
    Vec3 size{10.0f, 4.0f, 10.0f};
    Vec3 probes{4.0f, 2.0f, 4.0f};
    float intensity = 1.0f;
    bool visibility = true;
    bool enabled = true;
    constexpr bool operator==(const IrradianceVolume&) const = default;
};
void to_json(Json& j, const IrradianceVolume& v);
void from_json(const Json& j, IrradianceVolume& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(IrradianceVolume& v, std::string_view path, float** out);

/// An image laid onto whatever surfaces lie in a box (docs/design/rendering.md, Decals): a puddle, a stain, a painted marking, a sign's glow. The box is size across (x, y, z) centred on the entity and turned and scaled with it; the image spans its x and z and is projected along its -y, so an unturned decal paints the floor under it. It changes the surfaces' colour (and, when set, their roughness) before they are lit, fading where a surface turns away from the projection.
struct Decal {
    std::string texture = "";
    Color4 color{1.0f, 1.0f, 1.0f, 1.0f};
    Vec3 size{2.0f, 1.0f, 2.0f};
    float roughness = -1.0f;
    float emissive = 0.0f;
    std::string normal_map = "";
    float bumpiness = 1.0f;
    float angle = 60.0f;
    std::int32_t order = 0;
    bool enabled = true;
    constexpr bool operator==(const Decal&) const = default;
};
void to_json(Json& j, const Decal& v);
void from_json(const Json& j, Decal& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Decal& v, std::string_view path, float** out);

/// Air that thickens with distance and thins with height (docs/design/rendering.md, Fog): what is far fades toward the fog's color, a valley fills with it while the hilltops stay clear, and the sky's horizon melts into it. The first enabled one counts.
struct Fog {
    Color4 color{0.7f, 0.75f, 0.8f, 1.0f};
    float density = 0.03f;
    float height = 0.0f;
    float falloff = 0.2f;
    float start = 0.0f;
    float max_opacity = 1.0f;
    bool enabled = true;
    bool volumetric = false;
    float anisotropy = 0.6f;
    std::int32_t steps = 16;
    float distance = 60.0f;
    constexpr bool operator==(const Fog&) const = default;
};
void to_json(Json& j, const Fog& v);
void from_json(const Json& j, Fog& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Fog& v, std::string_view path, float** out);

/// The sky around the scene (docs/design/rendering.md, Sky and environment light): drawn behind everything, and the light the scene gets from all around: surfaces are lit by it (diffuse) and glossy ones mirror it (specular), in place of the flat ambient. The first enabled one counts; a 2D game leaves it out.
struct Sky {
    std::int32_t mode = 1;
    std::string image = "";
    Color4 zenith{0.25f, 0.45f, 0.8f, 1.0f};
    Color4 horizon{0.75f, 0.82f, 0.9f, 1.0f};
    Color4 ground{0.33f, 0.3f, 0.27f, 1.0f};
    float intensity = 1.0f;
    float rotation = 0.0f;
    float sun_size = 1.5f;
    float diffuse = 1.0f;
    float specular = 1.0f;
    float aerial = 1.0f;
    float haze = 1.0f;
    float clouds = 0.0f;
    float cloud_height = 1500.0f;
    float cloud_scale = 900.0f;
    float cloud_depth = -1.0f;
    float time_of_day = -1.0f;
    float day_length = 0.0f;
    float sun_height = 60.0f;
    bool enabled = true;
    constexpr bool operator==(const Sky&) const = default;
};
void to_json(Json& j, const Sky& v);
void from_json(const Json& j, Sky& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Sky& v, std::string_view path, float** out);

/// Draws a mesh: a built-in primitive or a glTF file from the project's assets, tinted by a color and optionally textured.
struct MeshRenderer {
    std::string mesh = "cube";
    std::string node = "";
    Color4 color{0.8f, 0.8f, 0.8f, 1.0f};
    std::string texture = "";
    float metallic = -1.0f;
    float roughness = -1.0f;
    Color4 emissive{0.0f, 0.0f, 0.0f, 1.0f};
    float cutoff = 0.0f;
    std::string normal_map = "";
    float transmission = -1.0f;
    float ior = -1.0f;
    float thickness = -1.0f;
    float clearcoat = -1.0f;
    float clearcoat_roughness = -1.0f;
    Color4 sheen{0.0f, 0.0f, 0.0f, 1.0f};
    float sheen_roughness = -1.0f;
    float specular = -1.0f;
    float anisotropy = -1.0f;
    float anisotropy_rotation = 0.0f;
    std::string material = "";
    Vec4 material_params{0.0f, 0.0f, 0.0f, 0.0f};
    float texture_tile = 0.0f;
    bool unlit = false;
    bool visible = true;
    Color4 highlight{0.0f, 0.0f, 0.0f, 0.0f};
    bool after_dark = false;
    bool cast_shadows = true;
    std::vector<MeshLod> lods = {};
    float cull_screen = 0.0f;
    constexpr bool operator==(const MeshRenderer&) const = default;
};
void to_json(Json& j, const MeshRenderer& v);
void from_json(const Json& j, MeshRenderer& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(MeshRenderer& v, std::string_view path, float** out);

/// A 2D image: a textured unit square in the entity's XY plane, sized in world units, unlit, alpha blended, drawn after meshes in layer order. Use with an orthographic camera looking down -Z.
struct Sprite {
    std::string texture = "";
    Vec2 size{1.0f, 1.0f};
    Color4 color{1.0f, 1.0f, 1.0f, 1.0f};
    Vec2 anchor{0.5f, 0.5f};
    std::int32_t layer = 0;
    Vec4 uv{0.0f, 0.0f, 1.0f, 1.0f};
    bool flip_x = false;
    bool flip_y = false;
    std::string filter = "linear";
    bool visible = true;
    bool sort_y = false;
    std::string material = "";
    Vec4 params{0.0f, 0.0f, 0.0f, 0.0f};
    bool additive = false;
    bool lit = false;
    std::string normal_map = "";
    constexpr bool operator==(const Sprite&) const = default;
};
void to_json(Json& j, const Sprite& v);
void from_json(const Json& j, Sprite& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Sprite& v, std::string_view path, float** out);

/// Plays a clip (a run of sheet frames registered with sprite.clip or [sprite_clips] in project.toml) on the entity's Sprite: every tick the engine advances time, picks the frame and writes Sprite.uv (and texture when the clip names one). Emits sprite.finished when a non-looping clip ends.
struct SpriteAnimation {
    std::string clip = "";
    bool playing = true;
    bool loop = true;
    float speed = 1.0f;
    float fps = 0.0f;
    std::int32_t frame = 0;
    float time = 0.0f;
    bool finished = false;
    constexpr bool operator==(const SpriteAnimation&) const = default;
};
void to_json(Json& j, const SpriteAnimation& v);
void from_json(const Json& j, SpriteAnimation& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(SpriteAnimation& v, std::string_view path, float** out);

/// Draws a Tiled map (a .tmj file in the project) with the entity at the map's top-left corner: tile (x, y) occupies world x from x*tile_size to (x+1)*tile_size and y from -(y+1)*tile_size to -y*tile_size, so rows go down as in Tiled. Every visible tile layer is one static mesh drawn unlit through the sprite path (docs/design/tilemaps.md); tilemap.* commands answer what is where, tilemap.set / tilemap.fill edit the map for every entity drawing it and tilemap.save writes it back.
struct TileMap {
    std::string map = "";
    std::string layer = "";
    float tile_size = 1.0f;
    Color4 color{1.0f, 1.0f, 1.0f, 1.0f};
    std::int32_t order = -10;
    bool visible = true;
    bool lit = false;
    bool shadows = false;
    constexpr bool operator==(const TileMap&) const = default;
};
void to_json(Json& j, const TileMap& v);
void from_json(const Json& j, TileMap& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(TileMap& v, std::string_view path, float** out);

/// A state machine that plays the entity's Animator (docs/design/animation.md, State machines): states play a clip or blend clips along a parameter, transitions move between them on conditions over parameters the script sets, each with a cross-fade. The engine writes the state it is in; animation.param and animation.trigger set parameters.
struct AnimationGraph {
    std::vector<AnimationState> states = {};
    std::vector<AnimationTransition> transitions = {};
    std::vector<AnimationParam> params = {};
    std::string state = "";
    float state_time = 0.0f;
    std::string error = "";
    bool enabled = true;
    constexpr bool operator==(const AnimationGraph&) const = default;
};
void to_json(Json& j, const AnimationGraph& v);
void from_json(const Json& j, AnimationGraph& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(AnimationGraph& v, std::string_view path, float** out);

/// Plays a timeline file (docs/design/timelines.md): keyed tracks that move the fields of entities' components over time, set others at moments, and events fired at times, on the simulation clock. A cutscene, a door's swing, a day's end.
struct Timeline {
    std::string path = "";
    float time = 0.0f;
    bool playing = true;
    float speed = 1.0f;
    bool loop = false;
    bool finished = false;
    std::string error = "";
    constexpr bool operator==(const Timeline&) const = default;
};
void to_json(Json& j, const Timeline& v);
void from_json(const Json& j, Timeline& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Timeline& v, std::string_view path, float** out);

/// Plays a glTF animation clip of the entity's MeshRenderer asset: every tick the engine advances time, samples the clip's keyframes into the file's node hierarchy and poses the skinned mesh (docs/design/animation.md). Emits animation.finished when a non-looping clip ends. Use animation.play / animation.stop, or set the fields directly.
struct Animator {
    std::string clip = "";
    bool playing = true;
    bool loop = true;
    float speed = 1.0f;
    float time = 0.0f;
    bool finished = false;
    std::vector<AnimationBlend> blends = {};
    float fade = 0.0f;
    float fade_time = 0.0f;
    std::string from_clip = "";
    float from_time = 0.0f;
    std::vector<AnimationLayer> layers = {};
    std::vector<AnimationCue> cues = {};
    std::int32_t root_motion = 0;
    std::string root = "";
    Vec3 root_delta{0.0f, 0.0f, 0.0f};
    bool root_rotation = false;
    float root_delta_yaw = 0.0f;
    bool locomotion = false;
    float walk_speed = 1.4f;
    float run_speed = 4.0f;
    std::string footsteps = "";
    float footstep_noise = 0.0f;
    constexpr bool operator==(const Animator&) const = default;
};
void to_json(Json& j, const Animator& v);
void from_json(const Json& j, Animator& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Animator& v, std::string_view path, float** out);

/// Holds the entity at a joint of an animated model (docs/design/animation.md, Attachments): a sword in a hand, a hat on a head, a lantern on a belt. Every tick, after the animation, its Transform is set so it sits at `offset`, turned by `rotation`, in the joint's frame; its own scale stays.
struct Attach {
    std::string target = "";
    std::string joint = "";
    Vec3 offset{0.0f, 0.0f, 0.0f};
    Quat rotation{0.0f, 0.0f, 0.0f, 1.0f};
    bool found = false;
    constexpr bool operator==(const Attach&) const = default;
};
void to_json(Json& j, const Attach& v);
void from_json(const Json& j, Attach& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Attach& v, std::string_view path, float** out);

/// Lets a skinned character go limp (docs/design/animation.md, Ragdolls). While active its bones are rigid bodies made from its mesh, a capsule for each bone fitted around the vertices that bone moves, held together at the joints by ball joints, falling and colliding with the world but not with each other or the entity's own collider, and its pose follows them instead of its clips. They are made from the pose it is in when it becomes active, moving as the entity was; off again, they go and the clips have the pose back.
struct Ragdoll {
    bool active = false;
    float mass = 70.0f;
    bool follow = true;
    std::int32_t bodies = 0;
    std::string root = "";
    constexpr bool operator==(const Ragdoll&) const = default;
};
void to_json(Json& j, const Ragdoll& v);
void from_json(const Json& j, Ragdoll& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Ragdoll& v, std::string_view path, float** out);

/// Inverse kinematics on a chain of the entity's skinned mesh: after the clips and layers pose the skeleton, the `bones` joints that end at node `end` bend so that the effector (`tip` in the end node's space) reaches `target` (world space) or the position of `target_entity`, solved by FABRIK with an optional pole (docs/design/animation.md, Inverse kinematics). Works without an Animator too (over the rest pose). Writes error and reached each tick; animation.pose reports the effector.
struct IK {
    std::string end = "";
    std::int32_t bones = 2;
    Vec3 tip{0.0f, 0.0f, 0.0f};
    Vec3 target{0.0f, 0.0f, 0.0f};
    std::string target_entity = "";
    std::string pole_entity = "";
    float max_bend = 180.0f;
    std::vector<IKLimit> limits = {};
    float weight = 1.0f;
    std::int32_t iterations = 8;
    float tolerance = 0.001f;
    float error = 0.0f;
    bool reached = false;
    float bend = 0.0f;
    constexpr bool operator==(const IK&) const = default;
};
void to_json(Json& j, const IK& v);
void from_json(const Json& j, IK& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(IK& v, std::string_view path, float** out);

/// Aims one node of the entity's skinned mesh at a point after the clips, layers and IK pose it: the node turns so that its `forward` axis points at `target` (world space) or at `target_entity`, at most `max_angle` degrees away from the posed direction, scaled by `weight` (docs/design/animation.md, Look-at). Writes angle each tick.
struct LookAt {
    std::string node = "";
    Vec3 forward{0.0f, 1.0f, 0.0f};
    Vec3 target{0.0f, 0.0f, 0.0f};
    std::string target_entity = "";
    float weight = 1.0f;
    float max_angle = 90.0f;
    float speed = 0.0f;
    float angle = 0.0f;
    Vec3 aim{0.0f, 0.0f, 0.0f};
    constexpr bool operator==(const LookAt&) const = default;
};
void to_json(Json& j, const LookAt& v);
void from_json(const Json& j, LookAt& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(LookAt& v, std::string_view path, float** out);

/// Spawns particles at the entity: small unlit quads (camera-facing billboards, or XY sprites) with a life, a velocity from a cone, gravity, drag, and size and color fading from start to end, landing on a floor, stretched along their motion, and bursting a child emitter where they die (docs/design/particles.md). Simulated by the engine on the fixed tick with a random stream seeded from the entity, so runs are deterministic. particles.burst emits a batch at once; particles.list reads the live ones.
struct ParticleEmitter {
    std::string texture = "";
    bool emitting = true;
    float rate = 20.0f;
    std::int32_t max = 256;
    Vec2 lifetime{1.0f, 2.0f};
    Vec2 speed{1.0f, 2.0f};
    Vec3 direction{0.0f, 1.0f, 0.0f};
    float spread = 30.0f;
    Vec3 gravity{0.0f, -3.0f, 0.0f};
    float drag = 0.0f;
    Vec2 size{0.2f, 0.05f};
    Color4 color{1.0f, 1.0f, 1.0f, 1.0f};
    Color4 color_end{1.0f, 1.0f, 1.0f, 0.0f};
    std::int32_t layer = 10;
    bool billboard = true;
    bool world_space = true;
    std::int32_t seed = 0;
    float floor = -1000000.0f;
    float bounce = 0.3f;
    float floor_friction = 0.5f;
    float stretch = 0.0f;
    std::uint64_t child = 0;
    std::int32_t child_count = 8;
    bool collide = false;
    bool additive = false;
    float turbulence = 0.0f;
    float turbulence_scale = 2.0f;
    Vec3 area{0.0f, 0.0f, 0.0f};
    bool gpu = false;
    constexpr bool operator==(const ParticleEmitter&) const = default;
};
void to_json(Json& j, const ParticleEmitter& v);
void from_json(const Json& j, ParticleEmitter& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(ParticleEmitter& v, std::string_view path, float** out);

/// A ribbon left behind by the entity as it moves (docs/design/particles.md, Trails): a blade's swing, a comet's tail, a car's tyre marks. Every tick a point is added where the entity (its offset) has got to once it is min_distance from the last, and points older than time go; the ribbon is drawn through them facing the camera (or flat in XY), its width and colour going from the newest point's to the oldest's. Visual only: not in the state hash.
struct Trail {
    float time = 0.5f;
    float width = 0.2f;
    float width_end = 0.0f;
    Color4 color{1.0f, 1.0f, 1.0f, 1.0f};
    Color4 color_end{1.0f, 1.0f, 1.0f, 0.0f};
    Vec3 offset{0.0f, 0.0f, 0.0f};
    float min_distance = 0.05f;
    bool emitting = true;
    bool billboard = true;
    bool additive = false;
    std::string texture = "";
    std::int32_t layer = 10;
    constexpr bool operator==(const Trail&) const = default;
};
void to_json(Json& j, const Trail& v);
void from_json(const Json& j, Trail& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Trail& v, std::string_view path, float** out);

/// Axis-aligned bounding box in world space, computed by the engine from the mesh and WorldTransform. Read only.
struct Bounds {
    Vec3 min{0.0f, 0.0f, 0.0f};
    Vec3 max{0.0f, 0.0f, 0.0f};
    constexpr bool operator==(const Bounds&) const = default;
};
void to_json(Json& j, const Bounds& v);
void from_json(const Json& j, Bounds& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Bounds& v, std::string_view path, float** out);

/// Physics body. Dynamic bodies fall and collide; static bodies never move; kinematic bodies move by their Velocity and push dynamic ones. A dynamic or kinematic body's Transform is its place in the world (the solver writes it back), so those should be roots; a static body under a parent (a node of an instantiated level) stands where its parents put it.
struct RigidBody {
    std::int32_t kind = 0;
    float mass = 1.0f;
    float restitution = 0.2f;
    float friction = 0.5f;
    float linear_damping = 0.01f;
    float angular_damping = 0.05f;
    float gravity_scale = 1.0f;
    bool sleeping = false;
    bool lock_rotation = false;
    bool ccd = false;
    constexpr bool operator==(const RigidBody&) const = default;
};
void to_json(Json& j, const RigidBody& v);
void from_json(const Json& j, RigidBody& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(RigidBody& v, std::string_view path, float** out);

/// Connects this body to another body, to any entity as a fixed point, or to a point in the world: a distance joint keeps two anchors a rod's length apart (or a rope's, pulling only; with stiffness it is a spring), a ball joint pins them together while both rotate freely, a hinge pins them and allows rotation about one axis only, a slider lets the body move along one axis only, each with optional limits and a motor (docs/design/physics.md, Joints). Solved with the contacts every tick; when the force carried exceeds break_force the joint breaks (joint.broken event, component removed).
struct Joint {
    std::int32_t kind = 0;
    std::string target = "";
    Vec3 anchor{0.0f, 0.0f, 0.0f};
    Vec3 target_anchor{0.0f, 0.0f, 0.0f};
    float distance = -1.0f;
    bool rope = false;
    float stiffness = 0.0f;
    float damping = 0.0f;
    float break_force = 0.0f;
    float force = 0.0f;
    Vec3 axis{0.0f, 0.0f, 1.0f};
    Vec3 target_axis{0.0f, 0.0f, 0.0f};
    Vec3 reference{0.0f, 0.0f, 0.0f};
    bool limit = false;
    float lower = -1.5708f;
    float upper = 1.5708f;
    float motor_speed = 0.0f;
    float motor_torque = 0.0f;
    float motor_force = 0.0f;
    float angle = 0.0f;
    float translation = 0.0f;
    float speed = 0.0f;
    bool collide_connected = true;
    constexpr bool operator==(const Joint&) const = default;
};
void to_json(Json& j, const Joint& v);
void from_json(const Json& j, Joint& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Joint& v, std::string_view path, float** out);

/// A 2D platformer body: an axis-aligned box in the XY plane that falls under gravity and is stopped by the solid tiles of a TileMap and by kinematic bodies (docs/design/tilemaps.md, 2D physics). Every tick the engine adds gravity, carries the body with the platform it rides, moves along X then Y, resolves against solid cells (one-way tiles only from above), walks slopes and steps, writes Transform.position and the contact flags, and emits body2d.landed. A kinematic body moves by its velocity alone and is a platform for the others. Scripts steer by writing velocity.
struct Body2D {
    Vec2 velocity{0.0f, 0.0f};
    float gravity = -24.0f;
    float max_fall = 30.0f;
    Vec2 size{0.4f, 0.5f};
    Vec2 offset{0.0f, 0.0f};
    std::string map = "";
    bool grounded = false;
    std::int32_t on_wall = 0;
    bool on_ceiling = false;
    bool kinematic = false;
    bool one_way = false;
    float step = 0.5f;
    std::uint64_t riding = 0;
    std::int32_t on_slope = 0;
    float mass = 1.0f;
    bool collide_bodies = true;
    float restitution = 0.0f;
    float friction = 0.0f;
    constexpr bool operator==(const Body2D&) const = default;
};
void to_json(Json& j, const Body2D& v);
void from_json(const Json& j, Body2D& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Body2D& v, std::string_view path, float** out);

/// A 3D character: an upright capsule centred on the entity that walks, climbs steps and slopes, stands on moving platforms and slides along walls, moved by the engine every tick after the rigid bodies (docs/design/physics.md, Characters). Scripts set velocity.x and z from input and velocity.y for a jump; the engine adds gravity, stops the capsule at every collider (static, kinematic and dynamic, triggers aside), and writes back where it stands. Give the entity a kinematic RigidBody and a capsule Collider of the same size too when rigid bodies should bump into it and triggers and raycasts should see it; the character passes over its own collider.
struct Character {
    Vec3 velocity{0.0f, 0.0f, 0.0f};
    float gravity = -20.0f;
    float max_fall = 50.0f;
    float radius = 0.3f;
    float height = 1.8f;
    float step = 0.3f;
    float max_slope = 45.0f;
    float push = 1.0f;
    float dive = 0.0f;
    float swim_speed = 0.6f;
    std::uint32_t mask = 4294967295;
    bool grounded = false;
    Vec3 ground_normal{0.0f, 1.0f, 0.0f};
    std::uint64_t ground = 0;
    bool on_wall = false;
    Vec3 wall_normal{0.0f, 0.0f, 0.0f};
    bool on_ceiling = false;
    bool stepped = false;
    bool swimming = false;
    float submerged = 0.0f;
    constexpr bool operator==(const Character&) const = default;
};
void to_json(Json& j, const Character& v);
void from_json(const Json& j, Character& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Character& v, std::string_view path, float** out);

/// Ground shaped by a height field (docs/design/terrain.md): a grid of heights across size.x by size.y (x by z) centred on the entity, from a greyscale heightmap image or from fractal noise, drawn with the entity's MeshRenderer (grass, rock on the slopes, snow up high) and collided with as a mesh by a Collider of shape 3; characters walk it, nav.bake maps it, and terrain.sculpt reshapes it.
struct Terrain {
    Vec2 size{64.0f, 64.0f};
    float height = 8.0f;
    std::int32_t resolution = 129;
    std::string heightmap = "";
    std::uint32_t seed = 1;
    float scale = 24.0f;
    std::int32_t octaves = 4;
    float island = 0.0f;
    Color4 grass{0.3f, 0.45f, 0.22f, 1.0f};
    Color4 rock{0.45f, 0.42f, 0.38f, 1.0f};
    Color4 snow{0.92f, 0.93f, 0.95f, 1.0f};
    float rock_slope = 35.0f;
    float snow_line = 0.85f;
    float texture_tile = 4.0f;
    float bump = 0.5f;
    float height_blend = 0.5f;
    std::string paintmap = "";
    std::vector<TerrainLayer> layers = {};
    std::string layermap = "";
    constexpr bool operator==(const Terrain&) const = default;
};
void to_json(Json& j, const Terrain& v);
void from_json(const Json& j, Terrain& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Terrain& v, std::string_view path, float** out);

/// A sheet of cloth hanging from the entity (docs/design/physics.md, Cloth): a flag, a cape, a curtain, a banner. Particles in a grid held to each other at their rest distances (along the weave, across it and two apart, so it bends but does not stretch), the pinned ones carried by the entity's transform, the rest pulled down by gravity, blown by the Wind and kept out of the colliders of the bodies around it. Drawn by the entity's MeshRenderer (its colour, texture and material) as a mesh the engine makes every tick, seen from both sides.
struct Cloth {
    Vec2 size{1.5f, 1.0f};
    Vec2 segments{12.0f, 8.0f};
    std::int32_t pin = 0;
    float stiffness = 0.9f;
    float damping = 0.02f;
    float weight = 0.4f;
    float wind = 1.0f;
    bool collide = true;
    float thickness = 0.02f;
    bool enabled = true;
    constexpr bool operator==(const Cloth&) const = default;
};
void to_json(Json& j, const Cloth& v);
void from_json(const Json& j, Cloth& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Cloth& v, std::string_view path, float** out);

/// The air's motion (docs/design/wind.md), one for the whole world: the first enabled Wind by id. Rigid bodies' linear_damping and particles' drag pull them toward the wind's velocity rather than to rest, so light things drift and smoke streams downwind; scattered copies that sway lean with it. Gusts run along it at its speed, the same on every run and every peer.
struct Wind {
    float direction = 0.0f;
    float speed = 3.0f;
    float gusts = 0.3f;
    float gust_length = 20.0f;
    bool enabled = true;
    constexpr bool operator==(const Wind&) const = default;
};
void to_json(Json& j, const Wind& v);
void from_json(const Json& j, Wind& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Wind& v, std::string_view path, float** out);

/// Rain and snow (docs/design/rendering.md, Weather), one for the whole world: the first enabled Weather by id. They fall in a box about the camera, slanted by the Wind; what they fall on gets wet (darker, glossier, most where it faces up) or white where snow lies, both building up while they fall and going after; an overcast sky dims the sun and, under an atmosphere, clouds it over.
struct Weather {
    float rain = 0.0f;
    float snow = 0.0f;
    float wet = 0.0f;
    float cover = 0.0f;
    float overcast = -1.0f;
    float density = 1.0f;
    float storm = 0.0f;
    float flash = 0.0f;
    bool sound = true;
    bool enabled = true;
    constexpr bool operator==(const Weather&) const = default;
};
void to_json(Json& j, const Weather& v);
void from_json(const Json& j, Weather& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Weather& v, std::string_view path, float** out);

/// A body of water (docs/design/water.md): a surface size.x by size.y (x by z) centred on the entity at its height, not turned with it, moved by waves; drawn after the solid scene, which shows through it bent by the waves and fading into its colour with depth, with the sky, the probes and the scene reflected at glancing angles and foam where it meets the shore. What floats in it (dynamic rigid bodies) is buoyed up and slowed, riding the same waves; water.height gives the surface anywhere.
struct Water {
    Vec2 size{40.0f, 40.0f};
    float depth = 4.0f;
    Color4 color{0.03f, 0.2f, 0.24f, 1.0f};
    float clarity = 4.0f;
    float wave_height = 0.3f;
    float wave_length = 8.0f;
    float wave_direction = 0.0f;
    float choppiness = 0.5f;
    float wind = 0.0f;
    float ripples = 1.0f;
    float foam = 0.5f;
    float caustics = 1.0f;
    Vec2 flow{0.0f, 0.0f};
    std::string course = "";
    float width = 4.0f;
    bool sound = true;
    bool ocean = false;
    float density = 2.0f;
    float drag = 1.0f;
    std::string splash = "";
    std::int32_t splash_count = 24;
    bool enabled = true;
    constexpr bool operator==(const Water&) const = default;
};
void to_json(Json& j, const Water& v);
void from_json(const Json& j, Water& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Water& v, std::string_view path, float** out);

/// Many copies of the entity's MeshRenderer strewn over the ground below it (docs/design/terrain.md, Scattering): grass, stones, flowers. From `seed`, `count` places are tried across `area` around the entity; each is dropped onto the static colliders under it (only `on`'s when set) and kept when the ground there is no steeper than max_slope, within min_height..max_height and at least `spacing` from the others; each gets a turn, a size and a shade of its own. The copies are drawn (and cast shadows) but are not entities and do not collide. Placed again when these settings, the entity's position or a terrain change.
struct Scatter {
    std::int32_t count = 500;
    Vec2 area{32.0f, 32.0f};
    std::uint32_t seed = 1;
    std::string on = "";
    Vec2 scale{0.8f, 1.2f};
    float yaw = 360.0f;
    float align = 0.0f;
    float sink = 0.0f;
    float spacing = 0.0f;
    float max_slope = 35.0f;
    float min_height = -1000.0f;
    float max_height = 1000.0f;
    float max_paint = 1.0f;
    float collide = 0.0f;
    float collide_height = 2.0f;
    float sway = 0.0f;
    float sway_speed = 0.5f;
    float fade = 0.0f;
    float shade = 0.15f;
    std::int32_t placed = 0;
    constexpr bool operator==(const Scatter&) const = default;
};
void to_json(Json& j, const Scatter& v);
void from_json(const Json& j, Scatter& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Scatter& v, std::string_view path, float** out);

/// A car on raycast wheels (docs/design/physics.md, Vehicles): on a dynamic RigidBody with a Collider, each Wheel's suspension is a spring cast down from its mount; wheels on the ground push the body up, drive it by `throttle`, turn it by `steer`, slow it by `brake` and keep it from sliding sideways by `grip`. Scripts set the controls; the engine writes speed and the wheels.
struct Vehicle {
    std::vector<Wheel> wheels = {};
    float throttle = 0.0f;
    float steer = 0.0f;
    float brake = 0.0f;
    float power = 10.0f;
    float top_speed = 25.0f;
    float braking = 18.0f;
    float max_steer = 30.0f;
    float grip = 1.4f;
    float suspension_hz = 2.2f;
    float damping = 0.45f;
    float roll_resistance = 0.3f;
    float speed = 0.0f;
    std::int32_t grounded = 0;
    constexpr bool operator==(const Vehicle&) const = default;
};
void to_json(Json& j, const Vehicle& v);
void from_json(const Json& j, Vehicle& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Vehicle& v, std::string_view path, float** out);

/// Blades of grass over the Terrain on the same entity (docs/design/terrain.md, Grass): made on the GPU round the camera, one a cell of a grid locked to the world, standing where the ground is gentle, high and low enough, unpainted and (with layers) of the layer named; thinning with the distance and bending in the Wind.
struct Grass {
    float density = 16.0f;
    float height = 0.5f;
    float width = 0.06f;
    Color4 color{0.24f, 0.42f, 0.14f, 1.0f};
    Color4 tip{0.55f, 0.68f, 0.3f, 1.0f};
    float reach = 40.0f;
    float thin = 12.0f;
    float sway = 0.6f;
    std::string layer = "";
    float max_slope = 35.0f;
    float min_height = -1000.0f;
    float max_height = 1000.0f;
    float max_paint = 0.3f;
    std::uint32_t seed = 1;
    bool enabled = true;
    constexpr bool operator==(const Grass&) const = default;
};
void to_json(Json& j, const Grass& v);
void from_json(const Json& j, Grass& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Grass& v, std::string_view path, float** out);

/// A boat (docs/design/physics.md, Boats): on a dynamic RigidBody with a Collider that floats on Water, the throttle drives it along its heading (-z), the rudder turns it (more the faster it goes), the keel holds it from sliding sideways and the sail takes the Wind's push, most with the wind on its quarter or beam and none heading into it. Scripts set the controls; the engine writes speed and afloat.
struct Boat {
    float throttle = 0.0f;
    float steer = 0.0f;
    float sail = 0.0f;
    float power = 4.0f;
    float top_speed = 8.0f;
    float turn_rate = 50.0f;
    float keel = 3.0f;
    float sail_power = 0.5f;
    float speed = 0.0f;
    bool afloat = false;
    constexpr bool operator==(const Boat&) const = default;
};
void to_json(Json& j, const Boat& v);
void from_json(const Json& j, Boat& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Boat& v, std::string_view path, float** out);

/// A box in the XY plane that notices 2D bodies (Body2D, TopDown2D) coming in and going out (docs/design/tilemaps.md, Areas): an `area.entered` and an `area.exited` event with the body as their subject and the area in their data, and how many are inside. A checkpoint, a pickup, a hazard, a door's trigger; it stops nothing.
struct Area2D {
    Vec2 size{0.5f, 0.5f};
    Vec2 offset{0.0f, 0.0f};
    bool enabled = true;
    std::int32_t inside = 0;
    constexpr bool operator==(const Area2D&) const = default;
};
void to_json(Json& j, const Area2D& v);
void from_json(const Json& j, Area2D& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Area2D& v, std::string_view path, float** out);

/// A line through points (docs/design/paths.md): a track, a patrol, a lane enemies walk, a platform's run, a camera's rail. The points are in the entity's own space, so its Transform moves, turns and scales the whole path. PathFollowers move along it; path.sample and path.nearest answer where on it a distance is and how far along a point lies.
struct Path {
    std::vector<PathPoint> points = {};
    bool closed = false;
    bool smooth = true;
    float length = 0.0f;
    constexpr bool operator==(const Path&) const = default;
};
void to_json(Json& j, const Path& v);
void from_json(const Json& j, Path& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Path& v, std::string_view path, float** out);

/// Moves its entity along a Path at a speed (docs/design/paths.md): a patrol, a car on a racing line, a platform on its run, a creep down a lane. Every tick before physics the engine moves `distance` on by `speed`, puts the Transform there (plus `offset`) and, with `orient`, turns it along the path; path.arrived and path.looped say when it comes to an end.
struct PathFollower {
    std::string path = "";
    float speed = 1.0f;
    float distance = 0.0f;
    std::int32_t mode = 0;
    std::int32_t orient = 0;
    Vec3 offset{0.0f, 0.0f, 0.0f};
    bool playing = true;
    bool finished = false;
    constexpr bool operator==(const PathFollower&) const = default;
};
void to_json(Json& j, const PathFollower& v);
void from_json(const Json& j, PathFollower& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(PathFollower& v, std::string_view path, float** out);

/// A 2D rigid body in the XY plane (docs/design/physics2d.md), simulated by Box2D: it turns about Z, and its Collider2D shapes collide with every other 2D rigid body and with the solid tiles of TileMaps, stacking, rolling and sliding with friction and bounce. The engine writes the Transform's X, Y and its turn about Z, and the velocities, after every step; a script that writes the Transform moves the body there, and one that writes a velocity sets it. Keep it a root. Not for an entity with a Body2D or TopDown2D (they move the Transform their own way).
struct RigidBody2D {
    std::int32_t kind = 0;
    Vec2 velocity{0.0f, 0.0f};
    float angular_velocity = 0.0f;
    float gravity_scale = 1.0f;
    float linear_damping = 0.0f;
    float angular_damping = 0.0f;
    bool fixed_rotation = false;
    bool bullet = false;
    bool awake = true;
    bool enabled = true;
    constexpr bool operator==(const RigidBody2D&) const = default;
};
void to_json(Json& j, const RigidBody2D& v);
void from_json(const Json& j, RigidBody2D& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(RigidBody2D& v, std::string_view path, float** out);

/// A 2D shape for the entity's RigidBody2D (docs/design/physics2d.md), or, on an entity without one, a static body of its own (a wall, a ramp, a sensor in the level). Sizes are in the entity's own units, multiplied by its Transform's scale.
struct Collider2D {
    std::int32_t shape = 0;
    Vec2 size{0.5f, 0.5f};
    float radius = 0.5f;
    Vec2 offset{0.0f, 0.0f};
    float angle = 0.0f;
    std::vector<Point2D> points = {};
    float density = 1.0f;
    float friction = 0.6f;
    float restitution = 0.0f;
    bool sensor = false;
    std::uint32_t layer = 1;
    std::uint32_t mask = 4294967295;
    constexpr bool operator==(const Collider2D&) const = default;
};
void to_json(Json& j, const Collider2D& v);
void from_json(const Json& j, Collider2D& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Collider2D& v, std::string_view path, float** out);

/// Two 2D rigid bodies held together (docs/design/physics2d.md): this entity's RigidBody2D and `body` (or a point fixed in the world when it names none). A hinge for a door or a wheel, a rope's length, a slider, a weld; a motor drives a hinge or a slider, a spring softens a weld or a length, and a joint pulled past `break_force` breaks.
struct Joint2D {
    std::int32_t kind = 0;
    std::uint64_t body = 0;
    Vec2 anchor{0.0f, 0.0f};
    Vec2 other_anchor{0.0f, 0.0f};
    Vec2 axis{1.0f, 0.0f};
    float length = -1.0f;
    float min_length = 0.0f;
    float max_length = 100000.0f;
    bool enable_limit = false;
    float lower = 0.0f;
    float upper = 0.0f;
    bool enable_motor = false;
    float motor_speed = 0.0f;
    float max_motor_force = 10.0f;
    bool enable_spring = false;
    float hertz = 4.0f;
    float damping_ratio = 0.7f;
    bool collide_connected = false;
    float break_force = 0.0f;
    constexpr bool operator==(const Joint2D&) const = default;
};
void to_json(Json& j, const Joint2D& v);
void from_json(const Json& j, Joint2D& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Joint2D& v, std::string_view path, float** out);

/// A top-down 2D mover on a tile map of any orientation (orthogonal, isometric, staggered, hexagonal; docs/design/tilemaps.md, Top-down bodies): a point with a radius in the XY plane that moves by its velocity, no gravity, and is stopped by the map's solid cells: the move is tried along X then along Y in steps no longer than the radius, so thin walls hold, and a step whose cell ahead is solid is dropped. Scripts set the velocity from input; the engine writes what was blocked and the cell under the center. Not for the same entity as a Body2D (both move the transform).
struct TopDown2D {
    Vec2 velocity{0.0f, 0.0f};
    float radius = 0.3f;
    std::string map = "";
    bool blocked_x = false;
    bool blocked_y = false;
    std::int32_t tile_x = -1;
    std::int32_t tile_y = -1;
    constexpr bool operator==(const TopDown2D&) const = default;
};
void to_json(Json& j, const TopDown2D& v);
void from_json(const Json& j, TopDown2D& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(TopDown2D& v, std::string_view path, float** out);

/// Collision shape centered on the entity (plus offset). Box half extents come from size; spheres use size.x as radius. Triggers report overlaps but do not push.
struct Collider {
    std::int32_t shape = 0;
    Vec3 size{0.5f, 0.5f, 0.5f};
    Vec3 offset{0.0f, 0.0f, 0.0f};
    bool is_trigger = false;
    std::string mesh = "";
    std::string node = "";
    std::uint32_t layer = 1;
    std::uint32_t mask = 4294967295;
    std::int32_t group = 0;
    constexpr bool operator==(const Collider&) const = default;
};
void to_json(Json& j, const Collider& v);
void from_json(const Json& j, Collider& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Collider& v, std::string_view path, float** out);

/// A sound attached to an entity: the engine starts it when autoplay is set (once, when the component appears or the scene loads) and keeps `playing` and `voice` current. Scripts use audio.play for one-shots.
struct AudioSource {
    std::string clip = "";
    float volume = 1.0f;
    float pitch = 1.0f;
    float lowpass = 1.0f;
    float reverb = 1.0f;
    std::string bus = "main";
    bool loop = false;
    bool autoplay = false;
    bool spatial = false;
    float near = 1.0f;
    float range = 20.0f;
    float occlusion = 0.0f;
    float doppler = 1.0f;
    bool occluded = false;
    bool playing = false;
    std::uint32_t voice = 0;
    constexpr bool operator==(const AudioSource&) const = default;
};
void to_json(Json& j, const AudioSource& v);
void from_json(const Json& j, AudioSource& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(AudioSource& v, std::string_view path, float** out);

/// Where spatial sounds are heard from: the entity's world position and facing stand in for the camera's while it is enabled (the first enabled one by entity id when there are several). Put it on the player of a third-person game so sounds are placed around the player, not the camera.
struct AudioListener {
    bool enabled = true;
    constexpr bool operator==(const AudioListener&) const = default;
};
void to_json(Json& j, const AudioListener& v);
void from_json(const Json& j, AudioListener& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(AudioListener& v, std::string_view path, float** out);

/// A moving thing paths go around (docs/design/navigation.md, Obstacles): every tick, before the agents move, the engine blocks the navigation cells within radius (plus the grid's agent radius) of the entity's position, so nav.path, nav.reachable, nav.nearest and the agents route around it without a new bake. Carts, crates, doors.
struct NavObstacle {
    float radius = 0.5f;
    bool enabled = true;
    constexpr bool operator==(const NavObstacle&) const = default;
};
void to_json(Json& j, const NavObstacle& v);
void from_json(const Json& j, NavObstacle& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(NavObstacle& v, std::string_view path, float** out);

/// A state machine for what a non-player character does (docs/design/behavior.md): states say how it moves (stay, follow, flee, wander, go home, patrol a path, through its NavAgent) and what entering them plays and says; transitions go between them on conditions over what it perceives (the distance to its target, whether it sees it, its health, a hit, time in the state, an event). Every change is a behavior.changed event, and the state is on the entity, so world.query shows what every guard is doing.
struct Behavior {
    std::string state = "";
    std::string previous = "";
    float time = 0.0f;
    std::vector<BehaviorState> states = {};
    std::vector<BehaviorTransition> transitions = {};
    std::uint64_t target = 0;
    std::string targets = "";
    Vec3 home{0.0f, -1000000.0f, 0.0f};
    float sight = 15.0f;
    float fov = 360.0f;
    float eye = 1.0f;
    std::int32_t waypoint = 0;
    Vec3 seen_at{0.0f, 0.0f, 0.0f};
    float unseen = 0.0f;
    float hearing = 1.0f;
    Vec3 heard_at{0.0f, 0.0f, 0.0f};
    float unheard = 0.0f;
    bool enabled = true;
    std::string error = "";
    constexpr bool operator==(const Behavior&) const = default;
};
void to_json(Json& j, const Behavior& v);
void from_json(const Json& j, Behavior& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Behavior& v, std::string_view path, float** out);

/// A thing that walks the navigation grid on its own (docs/design/navigation.md, Agents): every tick, after the scripts and the physics, the engine plans a path to its goal around the obstacles, heads for the next corner, picks the velocity that keeps it clear of the other agents and the obstacles, and moves the entity (Velocity.linear when it has a Velocity, else Transform.position). Scripts set mode, goal or target, speed and radius and read state; nav.arrived and nav.stuck are emitted on the transitions.
struct NavAgent {
    std::int32_t mode = 0;
    Vec3 goal{0.0f, 0.0f, 0.0f};
    std::uint64_t target = 0;
    Vec3 offset{0.0f, 0.0f, 0.0f};
    float speed = 3.0f;
    float radius = 0.35f;
    float arrive = 0.3f;
    std::int32_t replan = 10;
    float avoidance = 1.0f;
    float queue = 0.0f;
    bool face = false;
    float turn_speed = 540.0f;
    std::int32_t priority = 0;
    std::int32_t state = 0;
    Vec3 velocity{0.0f, 0.0f, 0.0f};
    Vec3 corner{0.0f, 0.0f, 0.0f};
    float distance = 0.0f;
    std::int32_t neighbours = 0;
    bool queued = false;
    constexpr bool operator==(const NavAgent&) const = default;
};
void to_json(Json& j, const NavAgent& v);
void from_json(const Json& j, NavAgent& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(NavAgent& v, std::string_view path, float** out);

/// Morph target weights set by script, over the ones the clip plays (docs/design/animation.md, Morph targets): every entry replaces the weight of its target for the entity's mesh asset; targets not listed keep the clip's or the file's default. animation.morph edits the list by name.
struct Morph {
    std::vector<MorphWeight> weights = {};
    constexpr bool operator==(const Morph&) const = default;
};
void to_json(Json& j, const Morph& v);
void from_json(const Json& j, Morph& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Morph& v, std::string_view path, float** out);

struct FieldInfo {
    std::string_view name;
    std::string_view type;   // "f32", "vec3", "list:AnimationLayer", ...
    std::string_view doc;
    std::span<const std::string_view> names;   // an i32 field's value names (index = value); empty for most
};

struct ComponentInfo {
    std::string_view name;
    std::string_view doc;
    bool serialized;
    std::span<const FieldInfo> fields;
};

struct RecordInfo {
    std::string_view name;
    std::span<const FieldInfo> fields;
};

/// Every component known to the engine, in metadata order.
std::span<const ComponentInfo> component_infos();
/// Every record (the values in list fields).
std::span<const RecordInfo> record_infos();

/// Hash a component value into a state hasher (all fields, in metadata order).
void hash_component(struct StateHasherRef& h, const Transform& v);
void hash_component(struct StateHasherRef& h, const WorldTransform& v);
void hash_component(struct StateHasherRef& h, const Velocity& v);
void hash_component(struct StateHasherRef& h, const Health& v);
void hash_component(struct StateHasherRef& h, const Hitbox& v);
void hash_component(struct StateHasherRef& h, const Model& v);
void hash_component(struct StateHasherRef& h, const Lifetime& v);
void hash_component(struct StateHasherRef& h, const Camera& v);
void hash_component(struct StateHasherRef& h, const CameraRig& v);
void hash_component(struct StateHasherRef& h, const Light& v);
void hash_component(struct StateHasherRef& h, const ReflectionProbe& v);
void hash_component(struct StateHasherRef& h, const IrradianceVolume& v);
void hash_component(struct StateHasherRef& h, const Decal& v);
void hash_component(struct StateHasherRef& h, const Fog& v);
void hash_component(struct StateHasherRef& h, const Sky& v);
void hash_component(struct StateHasherRef& h, const MeshRenderer& v);
void hash_component(struct StateHasherRef& h, const Sprite& v);
void hash_component(struct StateHasherRef& h, const SpriteAnimation& v);
void hash_component(struct StateHasherRef& h, const TileMap& v);
void hash_component(struct StateHasherRef& h, const AnimationGraph& v);
void hash_component(struct StateHasherRef& h, const Timeline& v);
void hash_component(struct StateHasherRef& h, const Animator& v);
void hash_component(struct StateHasherRef& h, const Attach& v);
void hash_component(struct StateHasherRef& h, const Ragdoll& v);
void hash_component(struct StateHasherRef& h, const IK& v);
void hash_component(struct StateHasherRef& h, const LookAt& v);
void hash_component(struct StateHasherRef& h, const ParticleEmitter& v);
void hash_component(struct StateHasherRef& h, const Trail& v);
void hash_component(struct StateHasherRef& h, const Bounds& v);
void hash_component(struct StateHasherRef& h, const RigidBody& v);
void hash_component(struct StateHasherRef& h, const Joint& v);
void hash_component(struct StateHasherRef& h, const Body2D& v);
void hash_component(struct StateHasherRef& h, const Character& v);
void hash_component(struct StateHasherRef& h, const Terrain& v);
void hash_component(struct StateHasherRef& h, const Cloth& v);
void hash_component(struct StateHasherRef& h, const Wind& v);
void hash_component(struct StateHasherRef& h, const Weather& v);
void hash_component(struct StateHasherRef& h, const Water& v);
void hash_component(struct StateHasherRef& h, const Scatter& v);
void hash_component(struct StateHasherRef& h, const Vehicle& v);
void hash_component(struct StateHasherRef& h, const Grass& v);
void hash_component(struct StateHasherRef& h, const Boat& v);
void hash_component(struct StateHasherRef& h, const Area2D& v);
void hash_component(struct StateHasherRef& h, const Path& v);
void hash_component(struct StateHasherRef& h, const PathFollower& v);
void hash_component(struct StateHasherRef& h, const RigidBody2D& v);
void hash_component(struct StateHasherRef& h, const Collider2D& v);
void hash_component(struct StateHasherRef& h, const Joint2D& v);
void hash_component(struct StateHasherRef& h, const TopDown2D& v);
void hash_component(struct StateHasherRef& h, const Collider& v);
void hash_component(struct StateHasherRef& h, const AudioSource& v);
void hash_component(struct StateHasherRef& h, const AudioListener& v);
void hash_component(struct StateHasherRef& h, const NavObstacle& v);
void hash_component(struct StateHasherRef& h, const Behavior& v);
void hash_component(struct StateHasherRef& h, const NavAgent& v);
void hash_component(struct StateHasherRef& h, const Morph& v);

/// A component's fields as plain numbers in metadata order (vectors by their parts, flags as 0 or 1),
/// for the scripts' path that skips JSON; kNotNumeric when a field is not a number (a string, an
/// entity, a list). write_numbers takes them back, false unless `n` is the count read gives.
inline constexpr std::size_t kNotNumeric = static_cast<std::size_t>(-1);
std::size_t read_numbers(const Transform& v, double* out);
bool write_numbers(Transform& v, const double* in, std::size_t n);
std::size_t read_numbers(const WorldTransform& v, double* out);
bool write_numbers(WorldTransform& v, const double* in, std::size_t n);
std::size_t read_numbers(const Velocity& v, double* out);
bool write_numbers(Velocity& v, const double* in, std::size_t n);
std::size_t read_numbers(const Health& v, double* out);
bool write_numbers(Health& v, const double* in, std::size_t n);
std::size_t read_numbers(const Hitbox& v, double* out);
bool write_numbers(Hitbox& v, const double* in, std::size_t n);
std::size_t read_numbers(const Model& v, double* out);
bool write_numbers(Model& v, const double* in, std::size_t n);
std::size_t read_numbers(const Lifetime& v, double* out);
bool write_numbers(Lifetime& v, const double* in, std::size_t n);
std::size_t read_numbers(const Camera& v, double* out);
bool write_numbers(Camera& v, const double* in, std::size_t n);
std::size_t read_numbers(const CameraRig& v, double* out);
bool write_numbers(CameraRig& v, const double* in, std::size_t n);
std::size_t read_numbers(const Light& v, double* out);
bool write_numbers(Light& v, const double* in, std::size_t n);
std::size_t read_numbers(const ReflectionProbe& v, double* out);
bool write_numbers(ReflectionProbe& v, const double* in, std::size_t n);
std::size_t read_numbers(const IrradianceVolume& v, double* out);
bool write_numbers(IrradianceVolume& v, const double* in, std::size_t n);
std::size_t read_numbers(const Decal& v, double* out);
bool write_numbers(Decal& v, const double* in, std::size_t n);
std::size_t read_numbers(const Fog& v, double* out);
bool write_numbers(Fog& v, const double* in, std::size_t n);
std::size_t read_numbers(const Sky& v, double* out);
bool write_numbers(Sky& v, const double* in, std::size_t n);
std::size_t read_numbers(const MeshRenderer& v, double* out);
bool write_numbers(MeshRenderer& v, const double* in, std::size_t n);
std::size_t read_numbers(const Sprite& v, double* out);
bool write_numbers(Sprite& v, const double* in, std::size_t n);
std::size_t read_numbers(const SpriteAnimation& v, double* out);
bool write_numbers(SpriteAnimation& v, const double* in, std::size_t n);
std::size_t read_numbers(const TileMap& v, double* out);
bool write_numbers(TileMap& v, const double* in, std::size_t n);
std::size_t read_numbers(const AnimationGraph& v, double* out);
bool write_numbers(AnimationGraph& v, const double* in, std::size_t n);
std::size_t read_numbers(const Timeline& v, double* out);
bool write_numbers(Timeline& v, const double* in, std::size_t n);
std::size_t read_numbers(const Animator& v, double* out);
bool write_numbers(Animator& v, const double* in, std::size_t n);
std::size_t read_numbers(const Attach& v, double* out);
bool write_numbers(Attach& v, const double* in, std::size_t n);
std::size_t read_numbers(const Ragdoll& v, double* out);
bool write_numbers(Ragdoll& v, const double* in, std::size_t n);
std::size_t read_numbers(const IK& v, double* out);
bool write_numbers(IK& v, const double* in, std::size_t n);
std::size_t read_numbers(const LookAt& v, double* out);
bool write_numbers(LookAt& v, const double* in, std::size_t n);
std::size_t read_numbers(const ParticleEmitter& v, double* out);
bool write_numbers(ParticleEmitter& v, const double* in, std::size_t n);
std::size_t read_numbers(const Trail& v, double* out);
bool write_numbers(Trail& v, const double* in, std::size_t n);
std::size_t read_numbers(const Bounds& v, double* out);
bool write_numbers(Bounds& v, const double* in, std::size_t n);
std::size_t read_numbers(const RigidBody& v, double* out);
bool write_numbers(RigidBody& v, const double* in, std::size_t n);
std::size_t read_numbers(const Joint& v, double* out);
bool write_numbers(Joint& v, const double* in, std::size_t n);
std::size_t read_numbers(const Body2D& v, double* out);
bool write_numbers(Body2D& v, const double* in, std::size_t n);
std::size_t read_numbers(const Character& v, double* out);
bool write_numbers(Character& v, const double* in, std::size_t n);
std::size_t read_numbers(const Terrain& v, double* out);
bool write_numbers(Terrain& v, const double* in, std::size_t n);
std::size_t read_numbers(const Cloth& v, double* out);
bool write_numbers(Cloth& v, const double* in, std::size_t n);
std::size_t read_numbers(const Wind& v, double* out);
bool write_numbers(Wind& v, const double* in, std::size_t n);
std::size_t read_numbers(const Weather& v, double* out);
bool write_numbers(Weather& v, const double* in, std::size_t n);
std::size_t read_numbers(const Water& v, double* out);
bool write_numbers(Water& v, const double* in, std::size_t n);
std::size_t read_numbers(const Scatter& v, double* out);
bool write_numbers(Scatter& v, const double* in, std::size_t n);
std::size_t read_numbers(const Vehicle& v, double* out);
bool write_numbers(Vehicle& v, const double* in, std::size_t n);
std::size_t read_numbers(const Grass& v, double* out);
bool write_numbers(Grass& v, const double* in, std::size_t n);
std::size_t read_numbers(const Boat& v, double* out);
bool write_numbers(Boat& v, const double* in, std::size_t n);
std::size_t read_numbers(const Area2D& v, double* out);
bool write_numbers(Area2D& v, const double* in, std::size_t n);
std::size_t read_numbers(const Path& v, double* out);
bool write_numbers(Path& v, const double* in, std::size_t n);
std::size_t read_numbers(const PathFollower& v, double* out);
bool write_numbers(PathFollower& v, const double* in, std::size_t n);
std::size_t read_numbers(const RigidBody2D& v, double* out);
bool write_numbers(RigidBody2D& v, const double* in, std::size_t n);
std::size_t read_numbers(const Collider2D& v, double* out);
bool write_numbers(Collider2D& v, const double* in, std::size_t n);
std::size_t read_numbers(const Joint2D& v, double* out);
bool write_numbers(Joint2D& v, const double* in, std::size_t n);
std::size_t read_numbers(const TopDown2D& v, double* out);
bool write_numbers(TopDown2D& v, const double* in, std::size_t n);
std::size_t read_numbers(const Collider& v, double* out);
bool write_numbers(Collider& v, const double* in, std::size_t n);
std::size_t read_numbers(const AudioSource& v, double* out);
bool write_numbers(AudioSource& v, const double* in, std::size_t n);
std::size_t read_numbers(const AudioListener& v, double* out);
bool write_numbers(AudioListener& v, const double* in, std::size_t n);
std::size_t read_numbers(const NavObstacle& v, double* out);
bool write_numbers(NavObstacle& v, const double* in, std::size_t n);
std::size_t read_numbers(const Behavior& v, double* out);
bool write_numbers(Behavior& v, const double* in, std::size_t n);
std::size_t read_numbers(const NavAgent& v, double* out);
bool write_numbers(NavAgent& v, const double* in, std::size_t n);
std::size_t read_numbers(const Morph& v, double* out);
bool write_numbers(Morph& v, const double* in, std::size_t n);

}  // namespace pocket::world
