// generated by `pocket gen`; do not edit
#pragma once

#define POCKET_COMPONENT_LIST(X) \
    X(Transform) \
    X(WorldTransform) \
    X(Velocity) \
    X(Health) \
    X(Lifetime) \
    X(Camera) \
    X(Light) \
    X(MeshRenderer) \
    X(Sprite) \
    X(SpriteAnimation) \
    X(TileMap) \
    X(Animator) \
    X(ParticleEmitter) \
    X(Bounds) \
    X(RigidBody) \
    X(Joint) \
    X(Collider) \
    X(AudioSource)
