// generated by `pocket gen`; do not edit
#pragma once

#define POCKET_COMPONENT_LIST(X) \
    X(Transform) \
    X(WorldTransform) \
    X(Velocity) \
    X(Health) \
    X(Hitbox) \
    X(Model) \
    X(Lifetime) \
    X(Camera) \
    X(CameraRig) \
    X(Light) \
    X(ReflectionProbe) \
    X(Decal) \
    X(Fog) \
    X(Sky) \
    X(MeshRenderer) \
    X(Sprite) \
    X(SpriteAnimation) \
    X(TileMap) \
    X(AnimationGraph) \
    X(Timeline) \
    X(Animator) \
    X(Attach) \
    X(IK) \
    X(LookAt) \
    X(ParticleEmitter) \
    X(Bounds) \
    X(RigidBody) \
    X(Joint) \
    X(Body2D) \
    X(Character) \
    X(Terrain) \
    X(Wind) \
    X(Water) \
    X(Scatter) \
    X(Vehicle) \
    X(Area2D) \
    X(TopDown2D) \
    X(Collider) \
    X(AudioSource) \
    X(AudioListener) \
    X(NavObstacle) \
    X(NavAgent) \
    X(Morph)
