// generated by `pocket gen` from engine/*/meta/*.toml; do not edit
#pragma once

#include <pocket/core/json.hpp>
#include <pocket/core/math.hpp>
#include <pocket/core/result.hpp>

#include <cstdint>
#include <span>
#include <string>
#include <string_view>
#include <vector>

namespace pocket::world {

struct Color4 {
    float r = 1, g = 1, b = 1, a = 1;
    constexpr bool operator==(const Color4&) const = default;
};

// Records: the values held by list fields of components.
/// One morph target weight set by script (docs/design/animation.md, Morph targets): the target by name or index, and the weight that replaces the clip's for it.
struct MorphWeight {
    std::string target = "";
    float weight = 0.0f;
    constexpr bool operator==(const MorphWeight&) const = default;
};
void to_json(Json& j, const MorphWeight& v);
void from_json(const Json& j, MorphWeight& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(MorphWeight& v, std::string_view path, float** out);
void hash_record(struct StateHasherRef& h, const MorphWeight& v);

/// The bend one joint of an IK chain may have, in degrees, measured between its bone and the bone above it, and, with `side`, the one way it bends (docs/design/animation.md, Inverse kinematics): the chain's `max_bend` is the default for the joints without an entry.
struct IKLimit {
    std::string joint = "";
    float min_bend = 0.0f;
    float max_bend = 180.0f;
    Vec3 side{0.0f, 0.0f, 0.0f};
    constexpr bool operator==(const IKLimit&) const = default;
};
void to_json(Json& j, const IKLimit& v);
void from_json(const Json& j, IKLimit& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(IKLimit& v, std::string_view path, float** out);
void hash_record(struct StateHasherRef& h, const IKLimit& v);

/// One clip layered over an Animator's base clip (docs/design/animation.md): sampled at its own time, limited to the nodes of `mask`, and either blended in at `weight` or added as the clip's change since its first frame. animation.layer adds, updates and removes layers.
struct AnimationLayer {
    std::string clip = "";
    float weight = 1.0f;
    std::string mask = "";
    bool additive = false;
    bool playing = true;
    bool loop = true;
    float speed = 1.0f;
    float time = 0.0f;
    constexpr bool operator==(const AnimationLayer&) const = default;
};
void to_json(Json& j, const AnimationLayer& v);
void from_json(const Json& j, AnimationLayer& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(AnimationLayer& v, std::string_view path, float** out);
void hash_record(struct StateHasherRef& h, const AnimationLayer& v);

/// Position, rotation and scale relative to the parent entity (or the world when there is no parent).
struct Transform {
    Vec3 position{0.0f, 0.0f, 0.0f};
    Quat rotation{0.0f, 0.0f, 0.0f, 1.0f};
    Vec3 scale{1.0f, 1.0f, 1.0f};
    constexpr bool operator==(const Transform&) const = default;
};
void to_json(Json& j, const Transform& v);
void from_json(const Json& j, Transform& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Transform& v, std::string_view path, float** out);

/// World-space transform computed from the Transform hierarchy every tick. Read only.
struct WorldTransform {
    Vec3 position{0.0f, 0.0f, 0.0f};
    Quat rotation{0.0f, 0.0f, 0.0f, 1.0f};
    Vec3 scale{1.0f, 1.0f, 1.0f};
    constexpr bool operator==(const WorldTransform&) const = default;
};
void to_json(Json& j, const WorldTransform& v);
void from_json(const Json& j, WorldTransform& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(WorldTransform& v, std::string_view path, float** out);

/// Linear and angular velocity. The built-in motion system integrates Transform from it every tick.
struct Velocity {
    Vec3 linear{0.0f, 0.0f, 0.0f};
    Vec3 angular{0.0f, 0.0f, 0.0f};
    constexpr bool operator==(const Velocity&) const = default;
};
void to_json(Json& j, const Velocity& v);
void from_json(const Json& j, Velocity& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Velocity& v, std::string_view path, float** out);

/// Hit points. Gameplay decides what zero means; the engine only stores and reports it.
struct Health {
    float current = 100.0f;
    float max = 100.0f;
    constexpr bool operator==(const Health&) const = default;
};
void to_json(Json& j, const Health& v);
void from_json(const Json& j, Health& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Health& v, std::string_view path, float** out);

/// Seconds remaining before the entity is destroyed by the lifetime system.
struct Lifetime {
    float seconds = 1.0f;
    constexpr bool operator==(const Lifetime&) const = default;
};
void to_json(Json& j, const Lifetime& v);
void from_json(const Json& j, Lifetime& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Lifetime& v, std::string_view path, float** out);

/// The renderer uses the first active camera. Perspective by default; orthographic for 2D (looking down -Z with +Y up is the 2D convention).
struct Camera {
    float fov_degrees = 60.0f;
    bool orthographic = false;
    float ortho_size = 5.0f;
    float near = 0.1f;
    float far = 1000.0f;
    bool active = true;
    constexpr bool operator==(const Camera&) const = default;
};
void to_json(Json& j, const Camera& v);
void from_json(const Json& j, Camera& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Camera& v, std::string_view path, float** out);

/// A light source. kind 0 = directional (shines along -Z of the entity), 1 = point.
struct Light {
    std::int32_t kind = 0;
    Color4 color{1.0f, 1.0f, 1.0f, 1.0f};
    float intensity = 1.0f;
    float range = 10.0f;
    constexpr bool operator==(const Light&) const = default;
};
void to_json(Json& j, const Light& v);
void from_json(const Json& j, Light& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Light& v, std::string_view path, float** out);

/// Air that thickens with distance and thins with height (docs/design/rendering.md, Fog): what is far fades toward the fog's color, a valley fills with it while the hilltops stay clear, and the sky's horizon melts into it. The first enabled one counts.
struct Fog {
    Color4 color{0.7f, 0.75f, 0.8f, 1.0f};
    float density = 0.03f;
    float height = 0.0f;
    float falloff = 0.2f;
    float start = 0.0f;
    float max_opacity = 1.0f;
    bool enabled = true;
    constexpr bool operator==(const Fog&) const = default;
};
void to_json(Json& j, const Fog& v);
void from_json(const Json& j, Fog& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Fog& v, std::string_view path, float** out);

/// The sky around the scene (docs/design/rendering.md, Sky and environment light): drawn behind everything, and the light the scene gets from all around: surfaces are lit by it (diffuse) and glossy ones mirror it (specular), in place of the flat ambient. The first enabled one counts; a 2D game leaves it out.
struct Sky {
    std::int32_t mode = 1;
    std::string image = "";
    Color4 zenith{0.25f, 0.45f, 0.8f, 1.0f};
    Color4 horizon{0.75f, 0.82f, 0.9f, 1.0f};
    Color4 ground{0.33f, 0.3f, 0.27f, 1.0f};
    float intensity = 1.0f;
    float rotation = 0.0f;
    float sun_size = 1.5f;
    float diffuse = 1.0f;
    float specular = 1.0f;
    bool enabled = true;
    constexpr bool operator==(const Sky&) const = default;
};
void to_json(Json& j, const Sky& v);
void from_json(const Json& j, Sky& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Sky& v, std::string_view path, float** out);

/// Draws a mesh: a built-in primitive or a glTF file from the project's assets, tinted by a color and optionally textured.
struct MeshRenderer {
    std::string mesh = "cube";
    std::string node = "";
    Color4 color{0.8f, 0.8f, 0.8f, 1.0f};
    std::string texture = "";
    float metallic = -1.0f;
    float roughness = -1.0f;
    Color4 emissive{0.0f, 0.0f, 0.0f, 1.0f};
    float cutoff = 0.0f;
    std::string normal_map = "";
    bool visible = true;
    constexpr bool operator==(const MeshRenderer&) const = default;
};
void to_json(Json& j, const MeshRenderer& v);
void from_json(const Json& j, MeshRenderer& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(MeshRenderer& v, std::string_view path, float** out);

/// A 2D image: a textured unit square in the entity's XY plane, sized in world units, unlit, alpha blended, drawn after meshes in layer order. Use with an orthographic camera looking down -Z.
struct Sprite {
    std::string texture = "";
    Vec2 size{1.0f, 1.0f};
    Color4 color{1.0f, 1.0f, 1.0f, 1.0f};
    Vec2 anchor{0.5f, 0.5f};
    std::int32_t layer = 0;
    Vec4 uv{0.0f, 0.0f, 1.0f, 1.0f};
    bool flip_x = false;
    bool flip_y = false;
    std::string filter = "linear";
    bool visible = true;
    bool sort_y = false;
    constexpr bool operator==(const Sprite&) const = default;
};
void to_json(Json& j, const Sprite& v);
void from_json(const Json& j, Sprite& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Sprite& v, std::string_view path, float** out);

/// Plays a clip (a run of sheet frames registered with sprite.clip or [sprite_clips] in project.toml) on the entity's Sprite: every tick the engine advances time, picks the frame and writes Sprite.uv (and texture when the clip names one). Emits sprite.finished when a non-looping clip ends.
struct SpriteAnimation {
    std::string clip = "";
    bool playing = true;
    bool loop = true;
    float speed = 1.0f;
    float fps = 0.0f;
    std::int32_t frame = 0;
    float time = 0.0f;
    bool finished = false;
    constexpr bool operator==(const SpriteAnimation&) const = default;
};
void to_json(Json& j, const SpriteAnimation& v);
void from_json(const Json& j, SpriteAnimation& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(SpriteAnimation& v, std::string_view path, float** out);

/// Draws a Tiled map (a .tmj file in the project) with the entity at the map's top-left corner: tile (x, y) occupies world x from x*tile_size to (x+1)*tile_size and y from -(y+1)*tile_size to -y*tile_size, so rows go down as in Tiled. Every visible tile layer is one static mesh drawn unlit through the sprite path (docs/design/tilemaps.md); tilemap.* commands answer what is where, tilemap.set / tilemap.fill edit the map for every entity drawing it and tilemap.save writes it back.
struct TileMap {
    std::string map = "";
    std::string layer = "";
    float tile_size = 1.0f;
    Color4 color{1.0f, 1.0f, 1.0f, 1.0f};
    std::int32_t order = -10;
    bool visible = true;
    constexpr bool operator==(const TileMap&) const = default;
};
void to_json(Json& j, const TileMap& v);
void from_json(const Json& j, TileMap& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(TileMap& v, std::string_view path, float** out);

/// Plays a glTF animation clip of the entity's MeshRenderer asset: every tick the engine advances time, samples the clip's keyframes into the file's node hierarchy and poses the skinned mesh (docs/design/animation.md). Emits animation.finished when a non-looping clip ends. Use animation.play / animation.stop, or set the fields directly.
struct Animator {
    std::string clip = "";
    bool playing = true;
    bool loop = true;
    float speed = 1.0f;
    float time = 0.0f;
    bool finished = false;
    float fade = 0.0f;
    float fade_time = 0.0f;
    std::string from_clip = "";
    float from_time = 0.0f;
    std::vector<AnimationLayer> layers = {};
    std::int32_t root_motion = 0;
    std::string root = "";
    Vec3 root_delta{0.0f, 0.0f, 0.0f};
    bool root_rotation = false;
    float root_delta_yaw = 0.0f;
    constexpr bool operator==(const Animator&) const = default;
};
void to_json(Json& j, const Animator& v);
void from_json(const Json& j, Animator& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Animator& v, std::string_view path, float** out);

/// Inverse kinematics on a chain of the entity's skinned mesh: after the clips and layers pose the skeleton, the `bones` joints that end at node `end` bend so that the effector (`tip` in the end node's space) reaches `target` (world space) or the position of `target_entity`, solved by FABRIK with an optional pole (docs/design/animation.md, Inverse kinematics). Works without an Animator too (over the rest pose). Writes error and reached each tick; animation.pose reports the effector.
struct IK {
    std::string end = "";
    std::int32_t bones = 2;
    Vec3 tip{0.0f, 0.0f, 0.0f};
    Vec3 target{0.0f, 0.0f, 0.0f};
    std::string target_entity = "";
    std::string pole_entity = "";
    float max_bend = 180.0f;
    std::vector<IKLimit> limits = {};
    float weight = 1.0f;
    std::int32_t iterations = 8;
    float tolerance = 0.001f;
    float error = 0.0f;
    bool reached = false;
    float bend = 0.0f;
    constexpr bool operator==(const IK&) const = default;
};
void to_json(Json& j, const IK& v);
void from_json(const Json& j, IK& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(IK& v, std::string_view path, float** out);

/// Aims one node of the entity's skinned mesh at a point after the clips, layers and IK pose it: the node turns so that its `forward` axis points at `target` (world space) or at `target_entity`, at most `max_angle` degrees away from the posed direction, scaled by `weight` (docs/design/animation.md, Look-at). Writes angle each tick.
struct LookAt {
    std::string node = "";
    Vec3 forward{0.0f, 1.0f, 0.0f};
    Vec3 target{0.0f, 0.0f, 0.0f};
    std::string target_entity = "";
    float weight = 1.0f;
    float max_angle = 90.0f;
    float speed = 0.0f;
    float angle = 0.0f;
    Vec3 aim{0.0f, 0.0f, 0.0f};
    constexpr bool operator==(const LookAt&) const = default;
};
void to_json(Json& j, const LookAt& v);
void from_json(const Json& j, LookAt& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(LookAt& v, std::string_view path, float** out);

/// Spawns particles at the entity: small unlit quads (camera-facing billboards, or XY sprites) with a life, a velocity from a cone, gravity, drag, and size and color fading from start to end, landing on a floor, stretched along their motion, and bursting a child emitter where they die (docs/design/particles.md). Simulated by the engine on the fixed tick with a random stream seeded from the entity, so runs are deterministic. particles.burst emits a batch at once; particles.list reads the live ones.
struct ParticleEmitter {
    std::string texture = "";
    bool emitting = true;
    float rate = 20.0f;
    std::int32_t max = 256;
    Vec2 lifetime{1.0f, 2.0f};
    Vec2 speed{1.0f, 2.0f};
    Vec3 direction{0.0f, 1.0f, 0.0f};
    float spread = 30.0f;
    Vec3 gravity{0.0f, -3.0f, 0.0f};
    float drag = 0.0f;
    Vec2 size{0.2f, 0.05f};
    Color4 color{1.0f, 1.0f, 1.0f, 1.0f};
    Color4 color_end{1.0f, 1.0f, 1.0f, 0.0f};
    std::int32_t layer = 10;
    bool billboard = true;
    bool world_space = true;
    std::int32_t seed = 0;
    float floor = -1000000.0f;
    float bounce = 0.3f;
    float floor_friction = 0.5f;
    float stretch = 0.0f;
    std::uint64_t child = 0;
    std::int32_t child_count = 8;
    bool collide = false;
    constexpr bool operator==(const ParticleEmitter&) const = default;
};
void to_json(Json& j, const ParticleEmitter& v);
void from_json(const Json& j, ParticleEmitter& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(ParticleEmitter& v, std::string_view path, float** out);

/// Axis-aligned bounding box in world space, computed by the engine from the mesh and WorldTransform. Read only.
struct Bounds {
    Vec3 min{0.0f, 0.0f, 0.0f};
    Vec3 max{0.0f, 0.0f, 0.0f};
    constexpr bool operator==(const Bounds&) const = default;
};
void to_json(Json& j, const Bounds& v);
void from_json(const Json& j, Bounds& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Bounds& v, std::string_view path, float** out);

/// Physics body. Dynamic bodies fall and collide; static bodies never move; kinematic bodies move by their Velocity and push dynamic ones. Uses the entity's Transform as world space (physics entities should be roots).
struct RigidBody {
    std::int32_t kind = 0;
    float mass = 1.0f;
    float restitution = 0.2f;
    float friction = 0.5f;
    float linear_damping = 0.01f;
    float angular_damping = 0.05f;
    float gravity_scale = 1.0f;
    bool sleeping = false;
    bool lock_rotation = false;
    bool ccd = false;
    constexpr bool operator==(const RigidBody&) const = default;
};
void to_json(Json& j, const RigidBody& v);
void from_json(const Json& j, RigidBody& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(RigidBody& v, std::string_view path, float** out);

/// Connects this body to another body, to any entity as a fixed point, or to a point in the world: a distance joint keeps two anchors a rod's length apart (or a rope's, pulling only; with stiffness it is a spring), a ball joint pins them together while both rotate freely, a hinge pins them and allows rotation about one axis only, a slider lets the body move along one axis only, each with optional limits and a motor (docs/design/physics.md, Joints). Solved with the contacts every tick; when the force carried exceeds break_force the joint breaks (joint.broken event, component removed).
struct Joint {
    std::int32_t kind = 0;
    std::string target = "";
    Vec3 anchor{0.0f, 0.0f, 0.0f};
    Vec3 target_anchor{0.0f, 0.0f, 0.0f};
    float distance = -1.0f;
    bool rope = false;
    float stiffness = 0.0f;
    float damping = 0.0f;
    float break_force = 0.0f;
    float force = 0.0f;
    Vec3 axis{0.0f, 0.0f, 1.0f};
    Vec3 target_axis{0.0f, 0.0f, 0.0f};
    Vec3 reference{0.0f, 0.0f, 0.0f};
    bool limit = false;
    float lower = -1.5708f;
    float upper = 1.5708f;
    float motor_speed = 0.0f;
    float motor_torque = 0.0f;
    float motor_force = 0.0f;
    float angle = 0.0f;
    float translation = 0.0f;
    float speed = 0.0f;
    bool collide_connected = true;
    constexpr bool operator==(const Joint&) const = default;
};
void to_json(Json& j, const Joint& v);
void from_json(const Json& j, Joint& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Joint& v, std::string_view path, float** out);

/// A 2D platformer body: an axis-aligned box in the XY plane that falls under gravity and is stopped by the solid tiles of a TileMap and by kinematic bodies (docs/design/tilemaps.md, 2D physics). Every tick the engine adds gravity, carries the body with the platform it rides, moves along X then Y, resolves against solid cells (one-way tiles only from above), walks slopes and steps, writes Transform.position and the contact flags, and emits body2d.landed. A kinematic body moves by its velocity alone and is a platform for the others. Scripts steer by writing velocity.
struct Body2D {
    Vec2 velocity{0.0f, 0.0f};
    float gravity = -24.0f;
    float max_fall = 30.0f;
    Vec2 size{0.4f, 0.5f};
    Vec2 offset{0.0f, 0.0f};
    std::string map = "";
    bool grounded = false;
    std::int32_t on_wall = 0;
    bool on_ceiling = false;
    bool kinematic = false;
    bool one_way = false;
    float step = 0.5f;
    std::uint64_t riding = 0;
    std::int32_t on_slope = 0;
    float mass = 1.0f;
    bool collide_bodies = true;
    float restitution = 0.0f;
    float friction = 0.0f;
    constexpr bool operator==(const Body2D&) const = default;
};
void to_json(Json& j, const Body2D& v);
void from_json(const Json& j, Body2D& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Body2D& v, std::string_view path, float** out);

/// A top-down 2D mover on a tile map of any orientation (orthogonal, isometric, staggered, hexagonal; docs/design/tilemaps.md, Top-down bodies): a point with a radius in the XY plane that moves by its velocity, no gravity, and is stopped by the map's solid cells: the move is tried along X then along Y in steps no longer than the radius, so thin walls hold, and a step whose cell ahead is solid is dropped. Scripts set the velocity from input; the engine writes what was blocked and the cell under the center. Not for the same entity as a Body2D (both move the transform).
struct TopDown2D {
    Vec2 velocity{0.0f, 0.0f};
    float radius = 0.3f;
    std::string map = "";
    bool blocked_x = false;
    bool blocked_y = false;
    std::int32_t tile_x = -1;
    std::int32_t tile_y = -1;
    constexpr bool operator==(const TopDown2D&) const = default;
};
void to_json(Json& j, const TopDown2D& v);
void from_json(const Json& j, TopDown2D& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(TopDown2D& v, std::string_view path, float** out);

/// Collision shape centered on the entity (plus offset). Box half extents come from size; spheres use size.x as radius. Triggers report overlaps but do not push.
struct Collider {
    std::int32_t shape = 0;
    Vec3 size{0.5f, 0.5f, 0.5f};
    Vec3 offset{0.0f, 0.0f, 0.0f};
    bool is_trigger = false;
    std::string mesh = "";
    std::uint32_t layer = 1;
    std::uint32_t mask = 4294967295;
    std::int32_t group = 0;
    constexpr bool operator==(const Collider&) const = default;
};
void to_json(Json& j, const Collider& v);
void from_json(const Json& j, Collider& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Collider& v, std::string_view path, float** out);

/// A sound attached to an entity: the engine starts it when autoplay is set (once, when the component appears or the scene loads) and keeps `playing` and `voice` current. Scripts use audio.play for one-shots.
struct AudioSource {
    std::string clip = "";
    float volume = 1.0f;
    float pitch = 1.0f;
    float lowpass = 1.0f;
    float reverb = 1.0f;
    bool loop = false;
    bool autoplay = false;
    bool spatial = false;
    float near = 1.0f;
    float range = 20.0f;
    float occlusion = 0.0f;
    bool occluded = false;
    bool playing = false;
    std::uint32_t voice = 0;
    constexpr bool operator==(const AudioSource&) const = default;
};
void to_json(Json& j, const AudioSource& v);
void from_json(const Json& j, AudioSource& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(AudioSource& v, std::string_view path, float** out);

/// Where spatial sounds are heard from: the entity's world position and facing stand in for the camera's while it is enabled (the first enabled one by entity id when there are several). Put it on the player of a third-person game so sounds are placed around the player, not the camera.
struct AudioListener {
    bool enabled = true;
    constexpr bool operator==(const AudioListener&) const = default;
};
void to_json(Json& j, const AudioListener& v);
void from_json(const Json& j, AudioListener& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(AudioListener& v, std::string_view path, float** out);

/// A moving thing paths go around (docs/design/navigation.md, Obstacles): every tick, before the agents move, the engine blocks the navigation cells within radius (plus the grid's agent radius) of the entity's position, so nav.path, nav.reachable, nav.nearest and the agents route around it without a new bake. Carts, crates, doors.
struct NavObstacle {
    float radius = 0.5f;
    bool enabled = true;
    constexpr bool operator==(const NavObstacle&) const = default;
};
void to_json(Json& j, const NavObstacle& v);
void from_json(const Json& j, NavObstacle& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(NavObstacle& v, std::string_view path, float** out);

/// A thing that walks the navigation grid on its own (docs/design/navigation.md, Agents): every tick, after the scripts and the physics, the engine plans a path to its goal around the obstacles, heads for the next corner, picks the velocity that keeps it clear of the other agents and the obstacles, and moves the entity (Velocity.linear when it has a Velocity, else Transform.position). Scripts set mode, goal or target, speed and radius and read state; nav.arrived and nav.stuck are emitted on the transitions.
struct NavAgent {
    std::int32_t mode = 0;
    Vec3 goal{0.0f, 0.0f, 0.0f};
    std::uint64_t target = 0;
    Vec3 offset{0.0f, 0.0f, 0.0f};
    float speed = 3.0f;
    float radius = 0.35f;
    float arrive = 0.3f;
    std::int32_t replan = 10;
    float avoidance = 1.0f;
    float queue = 0.0f;
    std::int32_t priority = 0;
    std::int32_t state = 0;
    Vec3 velocity{0.0f, 0.0f, 0.0f};
    Vec3 corner{0.0f, 0.0f, 0.0f};
    float distance = 0.0f;
    std::int32_t neighbours = 0;
    bool queued = false;
    constexpr bool operator==(const NavAgent&) const = default;
};
void to_json(Json& j, const NavAgent& v);
void from_json(const Json& j, NavAgent& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(NavAgent& v, std::string_view path, float** out);

/// Morph target weights set by script, over the ones the clip plays (docs/design/animation.md, Morph targets): every entry replaces the weight of its target for the entity's mesh asset; targets not listed keep the clip's or the file's default. animation.morph edits the list by name.
struct Morph {
    std::vector<MorphWeight> weights = {};
    constexpr bool operator==(const Morph&) const = default;
};
void to_json(Json& j, const Morph& v);
void from_json(const Json& j, Morph& v);
// Floats behind a numeric field path ("position", "position.x", "color", "layers.0.weight"); 0 when the path is not numeric.
std::size_t numeric_span(Morph& v, std::string_view path, float** out);

struct FieldInfo {
    std::string_view name;
    std::string_view type;
    std::string_view doc;
};

struct ComponentInfo {
    std::string_view name;
    std::string_view doc;
    bool serialized;
    std::span<const FieldInfo> fields;
};

/// Every component known to the engine, in metadata order.
std::span<const ComponentInfo> component_infos();

/// Hash a component value into a state hasher (all fields, in metadata order).
void hash_component(struct StateHasherRef& h, const Transform& v);
void hash_component(struct StateHasherRef& h, const WorldTransform& v);
void hash_component(struct StateHasherRef& h, const Velocity& v);
void hash_component(struct StateHasherRef& h, const Health& v);
void hash_component(struct StateHasherRef& h, const Lifetime& v);
void hash_component(struct StateHasherRef& h, const Camera& v);
void hash_component(struct StateHasherRef& h, const Light& v);
void hash_component(struct StateHasherRef& h, const Fog& v);
void hash_component(struct StateHasherRef& h, const Sky& v);
void hash_component(struct StateHasherRef& h, const MeshRenderer& v);
void hash_component(struct StateHasherRef& h, const Sprite& v);
void hash_component(struct StateHasherRef& h, const SpriteAnimation& v);
void hash_component(struct StateHasherRef& h, const TileMap& v);
void hash_component(struct StateHasherRef& h, const Animator& v);
void hash_component(struct StateHasherRef& h, const IK& v);
void hash_component(struct StateHasherRef& h, const LookAt& v);
void hash_component(struct StateHasherRef& h, const ParticleEmitter& v);
void hash_component(struct StateHasherRef& h, const Bounds& v);
void hash_component(struct StateHasherRef& h, const RigidBody& v);
void hash_component(struct StateHasherRef& h, const Joint& v);
void hash_component(struct StateHasherRef& h, const Body2D& v);
void hash_component(struct StateHasherRef& h, const TopDown2D& v);
void hash_component(struct StateHasherRef& h, const Collider& v);
void hash_component(struct StateHasherRef& h, const AudioSource& v);
void hash_component(struct StateHasherRef& h, const AudioListener& v);
void hash_component(struct StateHasherRef& h, const NavObstacle& v);
void hash_component(struct StateHasherRef& h, const NavAgent& v);
void hash_component(struct StateHasherRef& h, const Morph& v);

}  // namespace pocket::world
