//! Ninja file generation from the resolved graph.

use crate::graph::Graph;
use crate::manifest::Workspace;
use crate::toolchain::{self, Toolchain};
use anyhow::Result;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn esc(s: &str) -> String {
    s.replace('$', "$$").replace(' ', "$ ").replace(':', "$:")
}
fn pesc(p: &Path) -> String {
    esc(&p.to_string_lossy())
}
fn q(s: &str) -> String {
    if s.contains(' ') { format!("\"{}\"", s) } else { s.to_string() }
}

pub struct Generated {
    pub build_dir: PathBuf,
}

pub fn generate(ws: &Workspace, graph: &Graph, tc: &Toolchain, config: &str) -> Result<Generated> {
    let cfg = ws.config(config)?;
    let target = ws.target_of(config)?;
    let wasm = target == "wasm";
    let build_dir = ws.build_dir(config);
    toolchain::ensure_dir(&build_dir)?;
    let mut n = String::new();
    writeln!(n, "# generated by pocket; do not edit\nninja_required_version = 1.10\nbuilddir = .")?;
    writeln!(n, "cxx = {}\ncc = {}\nar = {}", q(&tc.cxx), q(&tc.cc), q(&tc.ar))?;
    let mut common: Vec<String> = vec![];
    // A cross target's triple and SDK (the iOS Simulator's), on every compile and link.
    let mut cross: Vec<String> = vec![];
    if let (Some(t), Some(s)) = (&tc.triple, &tc.sysroot) {
        cross.push(format!("-target {t}"));
        cross.push(format!("-isysroot {}", q(s)));
    }
    common.extend(cross.iter().cloned());
    if let Some(t) = &ws.file.toolchain.macos_deployment_target {
        if tc.host_os == "macos" && !wasm && cross.is_empty() {
            common.push(format!("-mmacosx-version-min={t}"));
        }
    }
    common.push("-fdiagnostics-absolute-paths".into());
    for d in ws.file.toolchain.defines.iter().chain(cfg.defines.iter()) {
        common.push(format!("-D{d}"));
    }
    let std_flag = format!("-std={}", ws.file.toolchain.cxx_standard);
    let warn = cfg.warnings.as_ref().unwrap_or(&ws.file.toolchain.warnings).join(" ");
    let cxxflags = format!("{} {} {} {}", std_flag, common.join(" "), ws.file.toolchain.cxx_flags.join(" "), cfg.cxx_flags.join(" "));
    // GNU C on Linux: glibc declares POSIX's clocks and sleeps (flecs uses them) only outside strict ISO C.
    let c_std = if tc.host_os == "linux" && !wasm { "gnu17" } else { "c17" };
    let cflags = format!("-std={c_std} {} {} {}", common.join(" "), ws.file.toolchain.c_flags.join(" "), cfg.c_flags.join(" "));
    writeln!(n, "cxxflags = {}\ncflags = {}\nwarn = {}", cxxflags, cflags, warn)?;
    writeln!(n, "rule cxx\n  command = $cxx -MD -MF $out.d $cxxflags $warn $flags -c $in -o $out\n  depfile = $out.d\n  deps = gcc\n  description = CXX $out")?;
    writeln!(n, "rule objcxx\n  command = $cxx -x objective-c++ -fobjc-arc -MD -MF $out.d $cxxflags $warn $flags -c $in -o $out\n  depfile = $out.d\n  deps = gcc\n  description = OBJCXX $out")?;
    writeln!(n, "rule cc\n  command = $cc -MD -MF $out.d $cflags $warn $flags -c $in -o $out\n  depfile = $out.d\n  deps = gcc\n  description = CC $out")?;
    writeln!(n, "rule ar\n  command = rm -f $out && $ar rcs $out $in\n  description = AR $out")?;
    // On Linux the static libraries go in a group (GNU-style linkers read archives once, in order)
    // and lld links; Apple's linker resolves archives in any order.
    let linux = tc.host_os == "linux" && !wasm;
    if linux {
        writeln!(n, "rule link\n  command = $cxx -fuse-ld=lld $ldflags -o $out -Wl,--start-group $in -Wl,--end-group $libs -ldl -lpthread -lm\n  description = LINK $out")?;
    } else {
        writeln!(n, "rule link\n  command = $cxx $ldflags -o $out $in $libs\n  description = LINK $out")?;
    }

    let mut targets = vec![];
    for (name, m) in &graph.modules {
        let mut flags: Vec<String> = vec![];
        for inc in &m.include_dirs {
            flags.push(format!("-I{}", inc.to_string_lossy()));
        }
        for d in &m.defines {
            flags.push(format!("-D{d}"));
        }
        let warn_override = if m.third_party { Some("-w".to_string()) } else { None };
        let mut objs = vec![];
        for src in &m.sources {
            let rel = toolchain::relative_to(src, &m.dir);
            let obj = build_dir.join("obj").join(name).join(format!("{}.o", rel.to_string_lossy()));
            let ext = src.extension().and_then(|e| e.to_str()).unwrap_or("");
            let (rule, extra) = match ext {
                "cpp" | "cc" | "cxx" => ("cxx", m.cxx_flags.join(" ")),
                "mm" if !wasm => ("objcxx", m.cxx_flags.join(" ")),
                "c" => ("cc", m.c_flags.join(" ")),
                "m" if !wasm => ("objcxx", m.c_flags.join(" ")),
                _ => continue,
            };
            writeln!(n, "build {}: {} {}", pesc(&obj), rule, pesc(src))?;
            writeln!(n, "  flags = {} {}", flags.join(" "), extra)?;
            if let Some(w) = &warn_override {
                writeln!(n, "  warn = {w}")?;
            }
            objs.push(obj);
        }
        let objs_str: Vec<String> = objs.iter().map(|o| pesc(o)).collect();
        match m.kind.as_str() {
            "static_library" => {
                let lib = build_dir.join("lib").join(format!("lib{name}.a"));
                if objs.is_empty() {
                    writeln!(n, "build {name}: phony")?;
                } else {
                    writeln!(n, "build {}: ar {}", pesc(&lib), objs_str.join(" "))?;
                    writeln!(n, "build {name}: phony {}", pesc(&lib))?;
                }
            }
            _ => {
                // Emscripten emits <name>.js plus <name>.wasm beside it.
                let exe = if wasm { build_dir.join("bin").join(format!("{}.js", m.output)) } else { build_dir.join("bin").join(&m.output) };
                let mut inputs = objs_str.clone();
                let mut libs: Vec<String> = vec![];
                for lm in &m.link_modules {
                    let Some(dep) = graph.modules.get(lm) else { continue };
                    if !dep.sources.is_empty() {
                        inputs.push(pesc(&build_dir.join("lib").join(format!("lib{lm}.a"))));
                    }
                }
                let mut frameworks: Vec<String> = if wasm { vec![] } else { m.frameworks.clone() };
                let mut weak: Vec<String> = vec![];
                let mut link_flags: Vec<String> = if wasm { vec![] } else { m.link_flags.clone() };
                for dn in &m.link_deps {
                    if let Some(d) = ws.dependency(dn) {
                        if !crate::deps::applies(d, &target) {
                            continue;
                        }
                        let pfx = crate::deps::prefix_for(ws, d, &target);
                        for l in &d.libs {
                            libs.push(pfx.join(l).to_string_lossy().into_owned());
                        }
                        if !wasm {
                            frameworks.extend(d.frameworks.iter().cloned());
                            weak.extend(d.weak_frameworks.iter().cloned());
                            link_flags.extend(d.link_flags.iter().cloned());
                        }
                    }
                }
                for f in dedup(frameworks) {
                    libs.push(format!("-framework {f}"));
                }
                for f in dedup(weak) {
                    libs.push(format!("-weak_framework {f}"));
                }
                libs.extend(dedup(link_flags));
                writeln!(n, "build {}: link {}", pesc(&exe), inputs.join(" "))?;
                writeln!(n, "  ldflags = {}", cross.iter().chain(cfg.link_flags.iter()).cloned().collect::<Vec<_>>().join(" "))?;
                writeln!(n, "  libs = {}", libs.join(" "))?;
                writeln!(n, "build {name}: phony {}", pesc(&exe))?;
            }
        }
        targets.push(name.clone());
    }
    writeln!(n, "build all: phony {}", targets.join(" "))?;
    writeln!(n, "default all")?;
    std::fs::write(build_dir.join("build.ninja"), n)?;
    Ok(Generated { build_dir })
}

fn dedup(v: Vec<String>) -> Vec<String> {
    let mut seen = indexmap::IndexSet::new();
    for x in v {
        seen.insert(x);
    }
    seen.into_iter().collect()
}
