//! Ninja file generation from the resolved graph.

use crate::graph::Graph;
use crate::manifest::Workspace;
use crate::toolchain::{self, Toolchain};
use anyhow::Result;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn esc(s: &str) -> String {
    s.replace('$', "$$").replace(' ', "$ ").replace(':', "$:")
}
fn pesc(p: &Path) -> String {
    esc(&p.to_string_lossy())
}
fn q(s: &str) -> String {
    if s.contains(' ') { format!("\"{}\"", s) } else { s.to_string() }
}

pub struct Generated {
    pub build_dir: PathBuf,
}

pub fn generate(ws: &Workspace, graph: &Graph, tc: &Toolchain, config: &str) -> Result<Generated> {
    let cfg = ws.config(config)?;
    let target = ws.target_of(config)?;
    let wasm = target == "wasm";
    // Native Windows: clang++ for the MSVC ABI, the dynamic C runtime (wgpu-native's Rust code
    // expects it), lld, llvm-lib, `.lib` and `.exe` names, and response files (no shell runs
    // Ninja's commands there, and a command line stops at 32 KiB).
    let windows = tc.host_os == "windows" && target == "native";
    let os = if windows { "windows" } else { "" };
    let build_dir = ws.build_dir(config);
    toolchain::ensure_dir(&build_dir)?;
    let mut n = String::new();
    writeln!(n, "# generated by pocket; do not edit\nninja_required_version = 1.10\nbuilddir = .")?;
    writeln!(n, "cxx = {}\ncc = {}\nar = {}", q(&tc.cxx), q(&tc.cc), q(&tc.ar))?;
    let mut common: Vec<String> = vec![];
    // A cross target's triple and SDK (the iOS Simulator's), on every compile and link.
    let mut cross: Vec<String> = vec![];
    if let (Some(t), Some(s)) = (&tc.triple, &tc.sysroot) {
        cross.push(format!("-target {t}"));
        cross.push(format!("-isysroot {}", q(s)));
    }
    common.extend(cross.iter().cloned());
    if let Some(t) = &ws.file.toolchain.macos_deployment_target {
        if tc.host_os == "macos" && !wasm && cross.is_empty() {
            common.push(format!("-mmacosx-version-min={t}"));
        }
    }
    common.push("-fdiagnostics-absolute-paths".into());
    if windows {
        common.push("-fms-runtime-lib=dll".into());
        // <windows.h> without min/max macros or the rarely used half; the C library's POSIX
        // names, functions without deprecation notes and M_PI; the standard library's conforming
        // over-aligned temporary buffers (std::stable_sort of 16-byte aligned draws); and none of
        // the string and vector annotations AddressSanitizer would add, which the linker refuses
        // to mix with the C++ dependencies CMake builds without it. Engine code calls the W
        // (UTF-16) Win32 functions by name.
        for d in ["NOMINMAX", "WIN32_LEAN_AND_MEAN", "_CRT_SECURE_NO_WARNINGS", "_CRT_NONSTDC_NO_DEPRECATE", "_USE_MATH_DEFINES", "_ENABLE_EXTENDED_ALIGNED_STORAGE", "_DISABLE_STRING_ANNOTATION", "_DISABLE_VECTOR_ANNOTATION"] {
            common.push(format!("-D{d}"));
        }
    }
    for d in ws.file.toolchain.defines.iter().chain(cfg.defines.iter()) {
        common.push(format!("-D{d}"));
    }
    let std_flag = format!("-std={}", ws.file.toolchain.cxx_standard);
    let warn = cfg.warnings.as_ref().unwrap_or(&ws.file.toolchain.warnings).join(" ");
    let cxxflags = format!("{} {} {} {}", std_flag, common.join(" "), ws.file.toolchain.cxx_flags.join(" "), cfg.cxx_flags.join(" "));
    // GNU C on Linux: glibc declares POSIX's clocks and sleeps (flecs uses them) only outside strict ISO C.
    let c_std = if tc.host_os == "linux" && !wasm { "gnu17" } else { "c17" };
    let cflags = format!("-std={c_std} {} {} {}", common.join(" "), ws.file.toolchain.c_flags.join(" "), cfg.c_flags.join(" "));
    writeln!(n, "cxxflags = {}\ncflags = {}\nwarn = {}", cxxflags, cflags, warn)?;
    writeln!(n, "rule cxx\n  command = $cxx -MD -MF $out.d $cxxflags $warn $flags -c $in -o $out\n  depfile = $out.d\n  deps = gcc\n  description = CXX $out")?;
    writeln!(n, "rule objcxx\n  command = $cxx -x objective-c++ -fobjc-arc -MD -MF $out.d $cxxflags $warn $flags -c $in -o $out\n  depfile = $out.d\n  deps = gcc\n  description = OBJCXX $out")?;
    writeln!(n, "rule cc\n  command = $cc -MD -MF $out.d $cflags $warn $flags -c $in -o $out\n  depfile = $out.d\n  deps = gcc\n  description = CC $out")?;
    if windows {
        // llvm-lib writes the archive afresh, so a removed source leaves no stale object.
        writeln!(n, "rule ar\n  command = $ar /nologo /out:$out @$out.rsp\n  rspfile = $out.rsp\n  rspfile_content = $in\n  description = AR $out")?;
    } else if tc.host_os == "windows" {
        // The web build from Windows: emar is llvm-ar, and no POSIX shell runs the rule.
        writeln!(n, "rule ar\n  command = cmd /c (if exist $out del /f /q $out) & $ar rcs $out @$out.rsp\n  rspfile = $out.rsp\n  rspfile_content = $in\n  description = AR $out")?;
    } else {
        writeln!(n, "rule ar\n  command = rm -f $out && $ar rcs $out $in\n  description = AR $out")?;
    }
    // On Linux the static libraries go in a group (GNU-style linkers read archives once, in order)
    // and lld links; Apple's linker resolves archives in any order, and so does lld-link.
    let linux = tc.host_os == "linux" && !wasm;
    if windows {
        // The response file is read with Windows quoting (backslashes are path separators). The
        // driver asks for the static C runtime (libcmt) whatever the objects say: refuse it, so
        // only the dynamic one they were compiled for is linked; `-D_DLL` is how it learns that
        // runtime for AddressSanitizer's thunk. An 8 MB main-thread stack as macOS gives
        // (Windows' default is 1 MB; JavaScriptCore sizes its limit from it), and debug
        // information into a PDB beside the executable. DbgHelp is flecs's (for backtraces; its
        // own request for it is made only under MSVC's compiler).
        writeln!(n, "rule link\n  command = $cxx -fuse-ld=lld -g -D_DLL -Wno-unused-command-line-argument $ldflags -o $out --rsp-quoting=windows @$out.rsp $libs -ldbghelp -Wl,/NODEFAULTLIB:libcmt -Wl,/STACK:8388608\n  rspfile = $out.rsp\n  rspfile_content = $in\n  description = LINK $out")?;
    } else if linux {
        writeln!(n, "rule link\n  command = $cxx -fuse-ld=lld $ldflags -o $out -Wl,--start-group $in -Wl,--end-group $libs -ldl -lpthread -lm\n  description = LINK $out")?;
    } else {
        writeln!(n, "rule link\n  command = $cxx $ldflags -o $out $in $libs\n  description = LINK $out")?;
    }
    // Windows: every executable carries windows.manifest (the UTF-8 code page, long paths) as a
    // resource that LLVM's resource compiler makes once per build directory.
    let manifest_res = if windows {
        write_if_changed(&build_dir.join("pocket.manifest"), include_str!("windows.manifest"))?;
        write_if_changed(&build_dir.join("pocket.rc"),"1 24 \"pocket.manifest\"\n")?;
        let rc = Path::new(&tc.cxx).with_file_name("llvm-rc.exe");
        writeln!(n, "rule rc\n  command = {} /nologo /fo $out $in\n  description = RC $out", q(&rc.to_string_lossy()))?;
        let res = build_dir.join("obj").join("pocket.res");
        writeln!(n, "build {}: rc {} | {}", pesc(&res), pesc(&build_dir.join("pocket.rc")), pesc(&build_dir.join("pocket.manifest")))?;
        Some(res)
    } else {
        None
    };

    let mut targets = vec![];
    for (name, m) in &graph.modules {
        let mut flags: Vec<String> = vec![];
        for inc in &m.include_dirs {
            flags.push(format!("-I{}", inc.to_string_lossy()));
        }
        for d in &m.defines {
            flags.push(format!("-D{d}"));
        }
        let warn_override = if m.third_party { Some("-w".to_string()) } else { None };
        let mut objs = vec![];
        for src in &m.sources {
            let rel = toolchain::relative_to(src, &m.dir);
            let obj = build_dir.join("obj").join(name).join(format!("{}.o", rel.to_string_lossy()));
            let ext = src.extension().and_then(|e| e.to_str()).unwrap_or("");
            let (rule, extra) = match ext {
                "cpp" | "cc" | "cxx" => ("cxx", m.cxx_flags.join(" ")),
                "mm" if !wasm => ("objcxx", m.cxx_flags.join(" ")),
                "c" => ("cc", m.c_flags.join(" ")),
                "m" if !wasm => ("objcxx", m.c_flags.join(" ")),
                _ => continue,
            };
            writeln!(n, "build {}: {} {}", pesc(&obj), rule, pesc(src))?;
            writeln!(n, "  flags = {} {}", flags.join(" "), extra)?;
            if let Some(w) = &warn_override {
                writeln!(n, "  warn = {w}")?;
            }
            objs.push(obj);
        }
        let objs_str: Vec<String> = objs.iter().map(|o| pesc(o)).collect();
        match m.kind.as_str() {
            "static_library" => {
                let lib = build_dir.join("lib").join(toolchain::static_lib_name(name, os));
                if objs.is_empty() {
                    writeln!(n, "build {name}: phony")?;
                } else {
                    writeln!(n, "build {}: ar {}", pesc(&lib), objs_str.join(" "))?;
                    writeln!(n, "build {name}: phony {}", pesc(&lib))?;
                }
            }
            _ => {
                // Emscripten emits <name>.js plus <name>.wasm beside it.
                let exe = if wasm { build_dir.join("bin").join(format!("{}.js", m.output)) } else { build_dir.join("bin").join(toolchain::exe_name(&m.output, os)) };
                let mut inputs = objs_str.clone();
                if let Some(res) = &manifest_res {
                    inputs.push(pesc(res));
                }
                let mut libs: Vec<String> = vec![];
                for lm in &m.link_modules {
                    let Some(dep) = graph.modules.get(lm) else { continue };
                    if !dep.sources.is_empty() {
                        inputs.push(pesc(&build_dir.join("lib").join(toolchain::static_lib_name(lm, os))));
                    }
                }
                let mut frameworks: Vec<String> = if wasm { vec![] } else { m.frameworks.clone() };
                let mut weak: Vec<String> = vec![];
                let mut link_flags: Vec<String> = if wasm { vec![] } else { m.link_flags.clone() };
                for dn in &m.link_deps {
                    if let Some(d) = ws.dependency(dn) {
                        if !crate::deps::applies(d, &target) {
                            continue;
                        }
                        let pfx = crate::deps::prefix_for(ws, d, &target);
                        for l in &d.libs {
                            libs.push(pfx.join(l).to_string_lossy().into_owned());
                        }
                        if !wasm {
                            frameworks.extend(d.frameworks.iter().cloned());
                            weak.extend(d.weak_frameworks.iter().cloned());
                            link_flags.extend(d.link_flags.iter().cloned());
                        }
                    }
                }
                for f in dedup(frameworks) {
                    libs.push(format!("-framework {f}"));
                }
                for f in dedup(weak) {
                    libs.push(format!("-weak_framework {f}"));
                }
                libs.extend(dedup(link_flags));
                writeln!(n, "build {}: link {}", pesc(&exe), inputs.join(" "))?;
                writeln!(n, "  ldflags = {}", cross.iter().chain(cfg.link_flags.iter()).cloned().collect::<Vec<_>>().join(" "))?;
                writeln!(n, "  libs = {}", libs.join(" "))?;
                writeln!(n, "build {name}: phony {}", pesc(&exe))?;
            }
        }
        targets.push(name.clone());
    }
    writeln!(n, "build all: phony {}", targets.join(" "))?;
    writeln!(n, "default all")?;
    std::fs::write(build_dir.join("build.ninja"), n)?;
    Ok(Generated { build_dir })
}

/// Writes a file only when its text changes, so Ninja does not rebuild what depends on it.
fn write_if_changed(path: &Path, text: &str) -> Result<()> {
    if std::fs::read_to_string(path).map(|old| old == text).unwrap_or(false) {
        return Ok(());
    }
    Ok(std::fs::write(path, text)?)
}

fn dedup(v: Vec<String>) -> Vec<String> {
    let mut seen = indexmap::IndexSet::new();
    for x in v {
        seen.insert(x);
    }
    seen.into_iter().collect()
}
