//! The files the code-health steps look at: those git tracks plus untracked files git does not
//! ignore (`git ls-files --cached --others --exclude-standard`, docs/spec/checks.md 5.1), so a new
//! file is checked before it is committed; and the glob patterns the configuration files use.

use std::path::Path;
use std::process::Command;

/// Repository-relative paths with `/` separators, sorted, of files that exist on disk (a tracked
/// file deleted in the working tree is gone for the check too).
pub fn list(root: &Path) -> Result<Vec<String>, String> {
    let out = Command::new("git")
        .args([
            "ls-files",
            "-z",
            "--cached",
            "--others",
            "--exclude-standard",
        ])
        .current_dir(root)
        .output()
        .map_err(|e| format!("git could not run: {e}"))?;
    if !out.status.success() {
        return Err(format!(
            "git ls-files failed: {}",
            String::from_utf8_lossy(&out.stderr).trim()
        ));
    }
    let mut files: Vec<String> = String::from_utf8_lossy(&out.stdout)
        .split('\0')
        .filter(|s| !s.is_empty())
        .map(|s| s.replace('\\', "/"))
        .filter(|s| root.join(s).is_file())
        .collect();
    files.sort();
    files.dedup();
    Ok(files)
}

/// Whether the first five lines hold `@generated`, the marker rustfmt recognizes
/// (`generated_marker_line_search_limit` is 5; checks.md 5.1).
pub fn is_generated(bytes: &[u8]) -> bool {
    let end = bytes
        .iter()
        .enumerate()
        .filter(|(_, b)| **b == b'\n')
        .nth(4)
        .map_or(bytes.len(), |(i, _)| i);
    String::from_utf8_lossy(&bytes[..end]).contains("@generated")
}

/// A glob over `/`-separated paths: `**` matches across directories (`a/**` matches everything
/// below `a`), `*` within one path component, `?` one character.
pub fn glob(pattern: &str, path: &str) -> bool {
    fn go(p: &[u8], s: &[u8]) -> bool {
        match p.first() {
            None => s.is_empty(),
            Some(b'*') if p.get(1) == Some(&b'*') => {
                let rest = if p.get(2) == Some(&b'/') {
                    &p[3..]
                } else {
                    &p[2..]
                };
                (0..=s.len())
                    .any(|i| (i == 0 || s[i - 1] == b'/' || rest.is_empty()) && go(rest, &s[i..]))
            }
            Some(b'*') => (0..=s.len())
                .take_while(|&i| i == 0 || s[i - 1] != b'/')
                .any(|i| go(&p[1..], &s[i..])),
            Some(b'?') => !s.is_empty() && s[0] != b'/' && go(&p[1..], &s[1..]),
            Some(c) => s.first() == Some(c) && go(&p[1..], &s[1..]),
        }
    }
    go(pattern.as_bytes(), path.as_bytes())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn globs() {
        assert!(glob("third_party/**", "third_party/a/b.rs"));
        assert!(!glob("third_party/**", "third_partyx/a.rs"));
        assert!(glob("shared/contract/*.md", "shared/contract/errors.md"));
        assert!(!glob(
            "shared/contract/*.md",
            "shared/contract/rust/README.md"
        ));
        assert!(glob("**/Cargo.lock", "Cargo.lock"));
        assert!(glob("**/Cargo.lock", "spikes/physics/Cargo.lock"));
        assert!(glob("samples/*/check.toml", "samples/sail/check.toml"));
        assert!(glob("a/?.rs", "a/b.rs"));
        assert!(!glob("a/?.rs", "a/bc.rs"));
    }

    #[test]
    fn generated_marker_in_the_first_five_lines_only() {
        assert!(is_generated(
            b"// @generated by cargo xtask gen\nfn main() {}\n"
        ));
        assert!(is_generated(b"1\n2\n3\n4\n# @generated\n"));
        assert!(!is_generated(b"1\n2\n3\n4\n5\n// @generated\n"));
    }
}
