//! P1 (docs/spec/persistence.md 12): the canonical encoding over a type covering every case of the
//! serde data model, generated by a seeded PCG32 in place of proptest (open choice 11):
//! `decode(encode(v)) == v`, `encode(decode(b)) == b` for every accepted `b` (mutated bytes
//! included), one test per rejection of 3.6, the skipped-field check, NaN refused in a component
//! while a cache holds an infinity; and schema fingerprints (versions.md 3.5).

mod common;

use std::collections::{BTreeMap, BTreeSet};
use std::fmt;

use pocket_persist::format::{ResolvedFormat, trace};
use pocket_persist::pce::{self, PceError};
use pocket_persist::{Fingerprint, SectionKey, SectionKind, snapshot};
use pocket_sim::{Event, EventInbox, EventKind, EventSeq, Pcg32, Persisted, PlainData, Tick};
use serde::de::{self, Visitor};
use serde::{Deserialize, Deserializer, Serialize, Serializer};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
struct UnitS;
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
struct Newtype(u16);
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
struct TupleS(i8, char);
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
enum E {
    A,
    B(i32),
    C(u8, bool),
    D { x: f32, y: Option<String> },
}

/// Bytes through `serialize_bytes`.
#[derive(Clone, Debug, PartialEq)]
struct Bytes(Vec<u8>);

impl Serialize for Bytes {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_bytes(&self.0)
    }
}

impl<'de> Deserialize<'de> for Bytes {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Bytes, D::Error> {
        struct V;
        impl<'de> Visitor<'de> for V {
            type Value = Bytes;
            fn expecting(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                f.write_str("bytes")
            }
            fn visit_bytes<Er: de::Error>(self, v: &[u8]) -> Result<Bytes, Er> {
                Ok(Bytes(v.to_vec()))
            }
        }
        d.deserialize_bytes(V)
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
struct Every {
    b: bool,
    i8: i8,
    i16: i16,
    i32: i32,
    i64: i64,
    i128: i128,
    u8: u8,
    u16: u16,
    u32: u32,
    u64: u64,
    u128: u128,
    f32: f32,
    f64: f64,
    c: char,
    s: String,
    bytes: Bytes,
    unit: (),
    unit_s: UnitS,
    nt: Newtype,
    tup: (u8, String),
    ts: TupleS,
    e: Vec<E>,
    opt: Option<u32>,
    map: BTreeMap<String, i16>,
    set: BTreeSet<u8>,
    arr: [u16; 3],
    nested: Vec<Vec<u8>>,
}

struct Gen(Pcg32);

impl Gen {
    fn u(&mut self) -> u64 {
        self.0.next_u64()
    }
    fn n(&mut self, max: u32) -> usize {
        self.0.below(max).unwrap() as usize
    }
    fn s(&mut self) -> String {
        let pool = ["", "a", "sloop", "é", "数据", "x y", "🙂", "\u{0}"];
        (0..self.n(4))
            .map(|_| pool[self.n(pool.len() as u32)])
            .collect()
    }
    fn c(&mut self) -> char {
        loop {
            if let Some(c) = char::from_u32(self.0.next_u32() % 0x11_0000) {
                return c;
            }
        }
    }
    fn f64(&mut self) -> f64 {
        match self.n(6) {
            0 => -0.0,
            1 => f64::from_bits(self.u()),
            2 => f64::MIN_POSITIVE / 3.0,
            _ => self.0.next_f64() * 1e6 - 5e5,
        }
    }
    fn e(&mut self) -> E {
        match self.n(4) {
            0 => E::A,
            1 => E::B(self.u() as i32),
            2 => E::C(self.u() as u8, self.u().is_multiple_of(2)),
            _ => E::D {
                x: f32::from_bits(self.u() as u32),
                y: (self.u().is_multiple_of(2)).then(|| self.s()),
            },
        }
    }
    fn every(&mut self) -> Every {
        Every {
            b: self.u().is_multiple_of(2),
            i8: self.u() as i8,
            i16: self.u() as i16,
            i32: self.u() as i32,
            i64: self.u() as i64,
            i128: ((self.u() as i128) << 64) | self.u() as i128,
            u8: self.u() as u8,
            u16: self.u() as u16,
            u32: self.u() as u32,
            u64: self.u(),
            u128: ((self.u() as u128) << 64) | self.u() as u128,
            f32: f32::from_bits(self.u() as u32),
            f64: self.f64(),
            c: self.c(),
            s: self.s(),
            bytes: Bytes((0..self.n(5)).map(|_| self.u() as u8).collect()),
            unit: (),
            unit_s: UnitS,
            nt: Newtype(self.u() as u16),
            tup: (self.u() as u8, self.s()),
            ts: TupleS(self.u() as i8, self.c()),
            e: (0..self.n(4)).map(|_| self.e()).collect(),
            opt: (self.u().is_multiple_of(2)).then(|| self.u() as u32),
            map: (0..self.n(4))
                .map(|_| (self.s(), self.u() as i16))
                .collect(),
            set: (0..self.n(5)).map(|_| self.u() as u8).collect(),
            arr: [self.u() as u16, self.u() as u16, self.u() as u16],
            nested: (0..self.n(3))
                .map(|_| (0..self.n(3)).map(|_| self.u() as u8).collect())
                .collect(),
        }
    }
}

fn enc<T: Serialize>(v: &T) -> Vec<u8> {
    let mut out = Vec::new();
    pce::encode_into(v, &mut out, false).unwrap();
    out
}

#[test]
fn p1_round_trip_and_canonical_bytes() {
    let mut g = Gen(Pcg32::new(2026, 10));
    let (mut accepted, mut refused) = (0, 0);
    for _ in 0..2000 {
        let v = g.every();
        let bytes = enc(&v);
        let back: Every = pce::from_bytes_canonical(&bytes, false).unwrap();
        // Bit-exact, NaN payloads and the sign of zero included.
        assert_eq!(enc(&back), bytes);
        if v.f64 == v.f64
            && v.f32 == v.f32
            && !v
                .e
                .iter()
                .any(|e| matches!(e, E::D { x, .. } if x.is_nan()))
        {
            assert_eq!(back, v);
        }
        assert_eq!(back.f64.to_bits(), v.f64.to_bits());
        // Mutated bytes: whatever decodes encodes back to exactly those bytes.
        for _ in 0..3 {
            let mut m = bytes.clone();
            let i = g.n(m.len() as u32);
            m[i] ^= 1 << g.n(8);
            match pce::from_bytes_canonical::<Every>(&m, false) {
                Ok(x) => {
                    assert_eq!(enc(&x), m, "accepted bytes re-encode to themselves");
                    accepted += 1;
                }
                Err(_) => refused += 1,
            }
        }
    }
    assert!(
        accepted > 100 && refused > 100,
        "{accepted} accepted, {refused} refused"
    );
}

fn refused<T: for<'de> Deserialize<'de> + fmt::Debug>(bytes: &[u8]) -> String {
    match pce::from_bytes::<T>(bytes, true) {
        Err(PceError::Noncanonical { reason, .. }) => reason,
        other => panic!("{bytes:?} gave {other:?}"),
    }
}

/// One test per rejection of 3.6.
#[test]
fn p1_rejections() {
    assert!(refused::<bool>(&[2]).contains("bool"));
    assert!(refused::<String>(&[2, 0xc3, 0x28]).contains("UTF-8"));
    assert!(refused::<char>(&0xd800u32.to_le_bytes()).contains("scalar"));
    assert!(refused::<String>(&[0x80, 0x00]).contains("trailing zero"));
    assert!(refused::<Option<u8>>(&[2, 0]).contains("option"));
    refused::<E>(&[4]);
    assert!(refused::<u8>(&[1, 2]).contains("left over"));
    assert!(refused::<f64>(&f64::NAN.to_bits().to_le_bytes()).contains("NaN"));
    #[derive(Debug, Deserialize)]
    #[serde(untagged)]
    #[allow(dead_code)]
    enum Untagged {
        A(u8),
    }
    assert!(refused::<Untagged>(&[1]).contains("deserialize_any"));
    assert!(matches!(
        pce::from_bytes::<Vec<u8>>(&[5, 1], true),
        Err(PceError::Truncated { .. })
    ));
    // A set out of order decodes (the decoder cannot see a container's order) but is not canonical.
    assert!(pce::from_bytes::<BTreeSet<u8>>(&[2, 5, 3], true).is_ok());
    assert!(matches!(
        pce::from_bytes_canonical::<BTreeSet<u8>>(&[2, 5, 3], true),
        Err(PceError::Noncanonical { .. })
    ));
    // Unsorted object keys in event data: the inbox's own decoding refuses them.
    let data = PlainData::Object(vec![
        ("b".into(), PlainData::Null),
        ("a".into(), PlainData::Null),
    ]);
    let event = Event {
        seq: EventSeq(1),
        tick: Tick(0),
        kind: EventKind::new("a.b").unwrap(),
        subject: None,
        cause: None,
        data,
    };
    #[derive(Serialize)]
    struct InboxRepr {
        events: Vec<Event>,
        boundary_from: u32,
    }
    let bytes = pce::to_bytes(&InboxRepr {
        events: vec![event],
        boundary_from: 0,
    })
    .unwrap();
    assert!(refused::<EventInbox>(&bytes).contains("order"));
}

/// The encoder refuses what a format without names cannot read back.
#[test]
fn p1_encoder_refusals() {
    #[derive(Serialize)]
    struct Skips {
        a: u8,
        #[serde(skip_serializing_if = "Option::is_none")]
        b: Option<u8>,
    }
    let e = pce::to_bytes(&Skips { a: 1, b: None }).unwrap_err();
    assert!(e.reason().contains("skip_serializing_if"), "{e}");
    assert!(pce::to_bytes(&Skips { a: 1, b: Some(2) }).is_ok());
    struct NoLen;
    impl Serialize for NoLen {
        fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
            use serde::ser::SerializeSeq;
            s.serialize_seq(None)?.end()
        }
    }
    assert!(
        pce::to_bytes(&NoLen)
            .unwrap_err()
            .reason()
            .contains("without a length")
    );
    assert!(pce::to_bytes(&f64::INFINITY).is_err());
    let mut out = Vec::new();
    pce::encode_into(&f64::INFINITY, &mut out, false).unwrap();
    assert_eq!(out, f64::INFINITY.to_bits().to_le_bytes());
}

/// A component field holding NaN is refused with `persist.encode` naming the entity, while a cache
/// section holding an infinity encodes.
#[test]
fn p1_nan_in_a_component_infinity_in_a_cache() {
    let mut g = common::game(1);
    let s = snapshot(g.sim.world(), &g.reg).unwrap();
    let counter = s
        .section(&SectionKey::new(SectionKind::Cache, "test.counter"))
        .unwrap();
    let c: common::Counter = pce::from_bytes(&counter.bytes, false).unwrap();
    assert_eq!(c.limit, f64::INFINITY);
    common::apply(
        &mut g.sim,
        "push",
        &serde_json::json!({"id": 2, "dx": f64::NAN, "dy": 0.0}),
    )
    .ok();
    let e2 = common::ent(&g.sim, 2).unwrap();
    g.sim
        .boundary()
        .world_mut()
        .get_mut::<common::Vel>(e2)
        .unwrap()
        .x = f64::NAN;
    let e = snapshot(g.sim.world(), &g.reg).unwrap_err();
    assert_eq!(e.code, "persist.encode");
    assert_eq!(e.detail["entity"], 2);
    assert_eq!(e.detail["section"], "component:Vel");
}

#[derive(Serialize, Deserialize)]
#[serde(rename = "Boat")]
struct BoatV1 {
    sail: f64,
    throttle: f64,
}
#[derive(Serialize, Deserialize)]
#[serde(rename = "Boat")]
struct BoatAdded {
    sail: f64,
    throttle: f64,
    reef: u8,
}
#[derive(Serialize, Deserialize)]
#[serde(rename = "Boat")]
struct BoatReordered {
    throttle: f64,
    sail: f64,
}
#[derive(Serialize, Deserialize)]
#[serde(rename = "Craft")]
struct BoatRenamed {
    sail: f64,
    throttle: f64,
}
macro_rules! boat {
    ($($t:ty),*) => { $(impl Persisted for $t { const NAME: &'static str = "Boat"; const VERSION: u32 = 1; })* };
}
boat!(BoatV1, BoatAdded, BoatReordered, BoatRenamed);

/// Fingerprints (versions.md 3.5): renaming the Rust struct changes nothing; adding or reordering a
/// field does. A recursive type (event data) resolves through a back reference.
#[test]
fn fingerprints() {
    let f = |r: ResolvedFormat| Fingerprint::of(&r);
    let v1 = f(trace::<BoatV1>().unwrap());
    assert_eq!(v1, f(trace::<BoatRenamed>().unwrap()));
    assert_ne!(v1, f(trace::<BoatAdded>().unwrap()));
    assert_ne!(v1, f(trace::<BoatReordered>().unwrap()));
    let inbox = trace::<EventInbox>().unwrap();
    assert!(format!("{inbox:?}").contains("Back(0)"), "{inbox:?}");
    let bag = trace::<common::Bag>().unwrap();
    let ResolvedFormat::Struct(fields) = &bag else {
        panic!("{bag:?}")
    };
    let names: Vec<&str> = fields.iter().map(|(n, _)| n.as_str()).collect();
    assert_eq!(names, ["items", "owner", "mood"]);
    assert!(matches!(&fields[2].1, ResolvedFormat::Enum(v) if v.len() == 2));
}
